### ISSUE TITLE
When will the code of NVDLA compiler be published？

### ISSUE THREAD

**Issue by JSnobody** [nvdla/sw#104]
Just title. 
Thanks！

**Comment by NienfengYao** [comment]
Please reference "[Where can I find nvdla_compiler tool? #68](https://github.com/nvdla/sw/issues/68)"
* we do not plan to open source full source code for compiler but we will release customizable compiler so that you can add your own layers.

**Comment by prasshantg** [comment]
@JSnobody @NienfengYao just in case you have not received notification, we have open sourced compiler code in latest release, please check it.
