### ISSUE TITLE
How to use sw/regression?

### ISSUE THREAD

**Issue by NienfengYao** [nvdla/sw#105]
Hi Guys,

Can someone tell me how to use it(sw/regression)?
Thanks.

**Comment by cnjsdfcy** [comment]
Hi Nienfeng,
可以简单描述下运行regression的步骤吗？
我的理解是：
首先，启动VP，并在其中运行: ./nvdla_runtime- s
然后，在host中运行kmdrun.py
不知我理解是否正确？
谢谢！

**Comment by arvindhbti** [comment]
Hi @NienfengYao @prasshantg 

I am getting this error.
Any solution please.

                                Test   CDP_L0_0                                 
################################################################################
Mon Sep 09 14:16:29 2019 on sandisk-usb-sys
Command: kmdrun.py --ssh --odir /home/sandisk/Desktop/nvdla/sw/regression/scripts/out/CDP_L0_0_66cb25 --guid 66cb25 -o output.log -t CDP_L0_0 --project dla --target sim --os linux --debug 0 --testhome /home/sandisk/Desktop/nvdla/sw/regression/flatbufs --goldhome /home/sandisk/Desktop/nvdla/sw/regression/golden --noclean --show
ssh cmd: ssh root@127.0.0.1 -p 6667 export LD_LIBRARY_PATH=/mnt && /mnt/nvdla_runtime -s
Waiting for server ready...
Failed to launch test server
Let's try again
ssh cmd: ssh root@127.0.0.1 -p 6667 "ps | grep '/mnt/nvdla_runtime -s' | awk '{print $1}' | xargs kill"
ssh cmd: ssh root@127.0.0.1 -p 6667 export LD_LIBRARY_PATH=/mnt && /mnt/nvdla_runtime -s
Waiting for server ready...
Failed to launch test server
Let's try again
ssh cmd: ssh root@127.0.0.1 -p 6667 "ps | grep '/mnt/nvdla_runtime -s' | awk '{print $1}' | xargs kill"
ssh cmd: ssh root@127.0.0.1 -p 6667 export LD_LIBRARY_PATH=/mnt && /mnt/nvdla_runtime -s
Waiting for server ready...
Failed to launch test server
Let's try again
ssh cmd: ssh root@127.0.0.1 -p 6667 "ps | grep '/mnt/nvdla_runtime -s' | awk '{print $1}' | xargs kill"
Launching test: python /home/sandisk/Desktop/nvdla/sw/regression/scripts/dla_client.py -i /home/sandisk/Desktop/nvdla/sw/regression/flatbufs/kmd/CDP/CDP_L0_0_fbuf -o /home/sandisk/Desktop/nvdla/sw/regression/scripts/out/CDP_L0_0_66cb25
Traceback (most recent call last):
  File "kmdrun.py", line 51, in <module>
    main()
  File "kmdrun.py", line 42, in main
    runScript.runTest()
  File "/home/sandisk/Desktop/nvdla/sw/regression/scripts/KmdRunScript.py", line 171, in runTest
    while self.serverlinebuffer:
AttributeError: 'KmdRunScript' object has no attribute 'serverlinebuffer'

@prasshantg please look into it.Thanks.
