### ISSUE TITLE
Error when execute ./nvdla_runtime

### ISSUE THREAD

**Issue by zhouweiscut** [nvdla/sw#112]
hi, 
when i run ./nvdla_runtime, it says that it is a "cannot execute binary file", but when i run ./nvdla_compiler, it has no error. details info shown as below.  i check these two files, one is based on x86-64,the other is based on ARM aarch64. why ? 

zhouwei@zhouwei-X555LD:./workspace/nvdla/sw/prebuilt/linux$ file nvdla_compiler 
nvdla_compiler: ELF 64-bit LSB executable, **x86-64**, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=aece394f2515a36599da6425347fe11f81aad1ca, with debug_info, not stripped
zhouwei@zhouwei-X555LD:./workspace/nvdla/sw/prebuilt/linux$ file nvdla_runtime 
nvdla_runtime: ELF 64-bit LSB executable, **ARM aarch64**, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=75e9e631671f0335de7fcaddee057340374da1f6, with debug_info, not stripped
zhouwei@zhouwei-X555LD:~/workspace/nvdla/sw/prebuilt/linux$ ./nvdla_runtime --loadable basic.nvdla
bash: ./nvdla_runtime: cannot execute binary file: Exec format error

**Comment by zhouweiscut** [comment]
thank you for your reply.
The reason why asking this question is that i want to generate registers configuration for Caffe-YOLOv2 based on corresponding hardware such as nv_full NVDLA, and then run a RTL simulation case on nv_full NVDLA.  but i haven't found any document describing this flow. do you have any suggestion ?

**Comment by prasshantg** [comment]
unfortunately, there is no document describing flow for this, you can study code at https://github.com/nvdla/sw/tree/master/kmd to dump registers for each layer being programmed.

**Comment by zhouweiscut** [comment]
> unfortunately, there is no document describing flow for this, you can study code at https://github.com/nvdla/sw/tree/master/kmd to dump registers for each layer being programmed.

ok, thank
