### ISSUE TITLE
About the out.dimg of AlexNet

### ISSUE THREAD

**Issue by smartchen2k** [nvdla/sw#115]
I have ran an AlexNet on the VP using the provided Compiler tool and Runtime tools. It costs almost 2 hours to inference a picture and generate the out.dimg. 
However, I downloaded word label from the internet, and found that the probability in out.dimg is not quite match the label.
So, any one has done this before, and what's your situation?
AlexNet network and parameters are download from the Caffe git. VP is for nv_full.

**Comment by xiao777dong** [comment]
Have  you solved the problem? I met the same problem. Thank you.
