### ISSUE TITLE
Different result between NN_L0_0_fbuf (prebuild) and Lenet (nvdla_compiler build)

### ISSUE THREAD

**Issue by HKLee2040** [nvdla/sw#12]
Use prebuild NN_L0_0_fbuf to test nvdla_runtime, the console shows the following message but own compiled version doesn't.

However, prebuild version can pass test but own compiled version was crash.

... skip ....
[ 1137.957393] INFO: rcu_preempt self-detected stall on CPU
[ 1137.957872] 0-...: (1 ticks this GP) idle=972/140000000000001/0 softirq=3004/3004 fqs=0
[ 1137.958250] (t=7844 jiffies g=1546 c=1545 q=1)
[ 1137.958621] rcu_preempt kthread starved for 7844 jiffies! g1546 c1545 f0x0 RCU_GP_WAIT_FQS(3) ->state=0x1
[ 1137.959066] rcu_preempt S 0 8 2 0x00000000
[ 1137.959411] Call trace:
[ 1137.959870] [] __switch_to+0x90/0xb0
[ 1137.960108] [] __schedule+0x19c/0x5e0
[ 1137.960286] [] schedule+0x38/0xa0
[ 1137.960442] [] schedule_timeout+0x12c/0x280
[ 1137.960627] [] rcu_gp_kthread+0x504/0x750
[ 1137.960804] [] kthread+0xfc/0x130
[ 1137.960966] [] ret_from_fork+0x10/0x50
[ 1137.961282] Task dump for CPU 0:
[ 1137.961423] nvdla_runtime R running task 0 1293 1259 0x0000000a
[ 1137.961698] Call trace:
[ 1137.961809] [] dump_backtrace+0x0/0x230
[ 1137.962044] [] show_stack+0x14/0x20
[ 1137.962245] [] sched_show_task+0x118/0x180
[ 1137.962455] [] dump_cpu_task+0x40/0x50
[ 1137.962649] [] rcu_dump_cpu_stacks+0x94/0xdc
[ 1137.962859] [] rcu_check_callbacks+0x7dc/0x9b0
[ 1137.963071] [] update_process_times+0x2c/0x60
[ 1137.963273] [] tick_sched_handle.isra.5+0x30/0x50
[ 1137.963492] [] tick_sched_timer+0x40/0x90
[ 1137.963699] [] __hrtimer_run_queues+0xec/0x160
[ 1137.963919] [] hrtimer_interrupt+0xa4/0x220
[ 1137.964135] [] arch_timer_handler_virt+0x30/0x40
[ 1137.964363] [] handle_percpu_devid_irq+0x78/0x130
[ 1137.964593] [] generic_handle_irq+0x24/0x40
[ 1137.964810] [] __handle_domain_irq+0x5c/0xc0
[ 1137.965026] [] gic_handle_irq+0x58/0xb0
[ 1137.965281] Exception stack(0xffff80003d9f38f0 to 0xffff80003d9f3a20)
[ 1137.965599] 38e0: ffff000009ec0000 ffff000009ecd00c
[ 1137.965908] 3900: 0000000000000017 ffff000000ac2008 ffff80003ca9ae00 ffff80003d4bab68
[ 1137.966198] 3920: ffff80003ca9ae00 ffff80003ca9ae00 0000000000000000 ffff80003d4babb0
[ 1137.966484] 3940: 0000000000000004 0000000000000040 ffff000008f02450 ffff000009008790
[ 1137.966772] 3960: ffff00000900838d ffff00008900837f ffff000008216980 0000ffffb382a460
[ 1137.967033] 3980: 0000000000000006 ffff000000ac6de8 ffff000000ac5c18 ffff000000abf2f8
[ 1137.967302] 39a0: 0000000000000000 ffff000000ac2008 ffff000000abf000 ffff000000ac3ac0
[ 1137.967583] 39c0: ffff000000abf6f8 0000000000000001 ffff000000ac2008 ffff80003d9f3a20
[ 1137.967822] 39e0: ffff000000abde54 ffff80003d9f3a20 ffff000000abde54 0000000060000145
[ 1137.968056] 3a00: ffff000000ac23c0 ffff000000ac5c18 0001000000000000 0000000400000000
[ 1137.968316] [] el1_irq+0xb4/0x128
[ 1137.969409] [] reg_write+0x1c/0x30 [opendla]
[ 1137.969701] [] dla_pdp_program+0x28c/0x64c [opendla]
[ 1137.969964] [] dla_program_operation+0x80/0x190 [opendla]
[ 1137.970274] [] dla_submit_operation+0x29c/0x330 [opendla]
[ 1137.970592] [] dla_execute_task+0x170/0x558 [opendla]
[ 1137.970936] [] nvdla_task_submit+0x30/0xb0 [opendla]
[ 1137.971480] [] nvdla_submit+0xf0/0x1b0 [opendla]
[ 1137.972130] [] drm_ioctl_kernel+0x6c/0xd4 [drm]
[ 1137.972585] [] drm_ioctl+0x298/0x3c4 [drm]
[ 1137.972786] [] do_vfs_ioctl+0xa4/0x750
[ 1137.972954] [] SyS_ioctl+0x8c/0xa0
[ 1137.973114] [] el0_svc_naked+0x24/0x28
... skip ...

**Comment by HKLee2040** [comment]
If I remove softmax in Lenet, the own compiled version can pass the test without the strange message.
Is there any error in prebuild NN_L0_0_fbuf?

**Comment by prasshantg** [comment]
@HKLee2040 we did not support softmax in compiler and it was part of test application, which is why compiled LeNet was showing strange messages. Pre-compiled LeNet i.e. NN_L0_0_fbuf was compiled by removing softmax from prototxt and hence it worked.

We have added softmax support to compiler, you should be able to use own compiler LeNet without any changes now. Please try with latest released compiler.

**Comment by HKLee2040** [comment]
Problem is solved.
