### ISSUE TITLE
Question: Does the nvdla_compiler for nv_large supporting Winograd convolution?

### ISSUE THREAD

**Issue by anakin1028** [nvdla/sw#121]
@prasshantg as we disscussed in #117, I feel maybe it's more clear to open a new issue for this question. Does the current compiler in the prebuilt folder support Winograd Convolution if all the constraints meet? If yes, do I need to configure anything to use this feature?

Thanks for your support!

**Comment by prasshantg** [comment]
Current compiler does not support full Winograd support. Our upcoming release in Q1 2019 will include full support for Winograd.

**Comment by mmaciag** [comment]
@prasshantg Speaking of Q1 2019, will the upcoming release also support nv_small, perhaps other configurations? Thanks.

**Comment by prasshantg** [comment]
It will support nv_large and nv_small

**Comment by shgoupf** [comment]
> It will support nv_large and nv_small

Awesome!!!! Looking forward for that release. Currently we have both nv_large and nv_small running with IBM CAPI FPGA. If we could have compiler support for those two configurations, it would enable a huge amount of possibilities.

**Comment by anakin1028** [comment]
@prasshantg thanks! Will the compiler source also release with this upcoming release?

**Comment by prasshantg** [comment]
Upcoming Q1 2019 release will not include source code. It will be mostly in the release after that.

**Comment by anakin1028** [comment]
Got it! Thanks for all your support!
