### ISSUE TITLE
is it intended to output nothing for sw regression test?

### ISSUE THREAD

**Issue by arcbbb** [nvdla/sw#13]
I just noticed that every `o_000000.dimg` in `sw/regression/golden/*/dla/` is an empty file.
And the result from command `nvdla_runtime` is just a single line of  Test Pass.
I expected obtaining a vector of inference result after running 
```bash
nvdla_runtime --softmax --image ../../regression/images/digits/eight.pgm \
--loadable ../../regression/flatbufs/kmd/NN/NN_L0_0_fbuf
```
What could I do for this?

Does it work to do something like this?
```diff
diff --git a/umd/tests/runtime/RuntimeTest.cpp b/umd/tests/runtime/RuntimeTest.cpp
index 10d6b95..3fdf223 100644
--- a/umd/tests/runtime/RuntimeTest.cpp
+++ b/umd/tests/runtime/RuntimeTest.cpp
@@ -315,10 +315,13 @@ static NvDlaError postProcessTest(const TestAppArgs* appArgs, TestInfo* i, NvDla
         {
             sumexp += expf(float(pSrc[ii])-maxval);
         }
+        NvDlaDebugPrintf("Result:\n");
         for (NvU32 ii=0; ii < pOutput->m_meta.channel; ii++)
         {
             pDst[ii] = expf(float(pSrc[ii])-maxval) / sumexp;
+            NvDlaDebugPrintf("%lf ", pDst[ii]);
         }
+        NvDlaDebugPrintf("\n");

         pOutput->m_pData = pDst;
     }
```
Thanks

**Comment by JunningWu** [comment]
I still wonder why the inference process does not generate any result about NUMs or Labels?
Maybe the "Test Pass" does not mean that the inference is right, It simplely means the process is done without any error.

**Comment by JunningWu** [comment]
@arcbbb I changed the the source file of RuntimeTest.cpp the same as yours, and recompile the nvdla_runtime, but the results are all zeros.

Lenet-5, without softmax layer.

**Comment by arcbbb** [comment]
@JunningWu Thanks for the try. I expect they could provide an example that retrieves the result from DLA HW.
From this commit f914c0c97bfec6d0087250308e9d37c6478d5bb1, it is obvious they didn't retrieve any result from DLA HW, therefore the MD5sums are the all same.

**Comment by prasshantg** [comment]
will add this feature in next release

**Comment by arcbbb** [comment]
It is nice to hear that, thanks!
