### ISSUE TITLE
Problems installing Virtual Platform

### ISSUE THREAD

**Issue by javiergcanada** [nvdla/sw#134]
I am trying to install the Virtual Platform on my system Ubuntu 18.04.2 LTS.
However, I am experiencing some problems when trying to build the NVDLA CMOD (executing the make in the _hw_ folder). When I am asked for where my perl, java, gcc and c++ are installed I introduce _/usr/bin_, where I have them installed. After executing _make_ with these values I get an error in the next step: **tools/bin/tmake -build cmod_top**, telling me that the permission to use _/usr/bin_ as those targets was denied. I have already tried to execute the _make_ instruction as well as the _build_ one as _sudo_ and I still get the same message.
Please someone tell me if they have experienced similar issues and how could I solve them. I am using this system for a class project and I am working on a tight schedule.
Thank you.

PS: I attach screenshot:
![Captura](https://user-images.githubusercontent.com/48141624/55201570-92696800-5191-11e9-8356-cb7cc86ec66a.PNG)

**Comment by prasshantg** [comment]
Issue looks similar to https://github.com/nvdla/sw/issues/134 since both are trying to solve VP installation problem. Closing as duplicate.

**Comment by prasshantg** [comment]
@javiergcanada please follow up on your issue in https://github.com/nvdla/sw/issues/134

**Comment by mmaciag** [comment]
> Issue looks similar to #134 since both are trying to solve VP installation problem. Closing as duplicate.

> @javiergcanada please follow up on your issue in #134

Shall we have April Fools' Day earlier this year or just accidental self-reference? :)

**Comment by prasshantg** [comment]
:) thanks for pointing out, it was accidental. Correct issue to refer is https://github.com/nvdla/hw/issues/277

**Comment by Kunal-es** [comment]
NVDLA Cmod library not found

**Comment by long771** [comment]
这是来自QQ邮箱的自动回复邮件。 您好，我是龙欣荣，很高兴收到您的邮件，我将尽快处理。

**Comment by Kunal-es** [comment]
Could you pls share NVDLA VP installation process here?
while compilation under VP terminal i am facing some issues as given below-->
1.  CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.
CMake Error at CMakeLists.txt:65 (message):
  NVDLA CMOD library not found.

2. under VP i am compiling nv_small file --> cmake -DCMAKE_INSTALL_PREFIX=build -DSYSTEMC_PREFIX=/usr/local/systemc-2.3.0/ -DNVDLA_HW_PREFIX=</usr/local/systemc-2.3.0> [-DNVDLA_HW_PROJECT=nv_small 
![Screenshot (104)](https://user-images.githubusercontent.com/67180159/187418615-ed05d2dd-69aa-47e8-a70c-c18a06563894.png)

3. Here i am going to share hw/Outdir log file also -->build.log file 
![Screenshot (105)](https://user-images.githubusercontent.com/67180159/187420042-6e9b6199-10fa-43af-8576-6c785820e345.png)
