### ISSUE TITLE
Virtual Simulator make problem

### ISSUE THREAD

**Issue by long-a-zhang-tieto** [nvdla/sw#135]
[  0%] Building CXX object libs/greenlib/greenreg/lib/CMakeFiles/greenreg.dir/__/src/greenreg.cpp.o
In file included from /usr/local/systemc-2.3.0/include/sysc/packages/boost/mem_fn.hpp:25:0,
                 from /usr/local/systemc-2.3.0/include/sysc/packages/boost/bind.hpp:26,
                 from /usr/local/systemc-2.3.0/include/sysc/kernel/sc_boost.h:44,
                 from /usr/local/systemc-2.3.0/include/sysc/kernel/sc_dynamic_processes.h:36,
                 from /usr/local/systemc-2.3.0/include/systemc:124,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/include/greenreg/sysc_ext/utils/gr_report.h:50,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/include/greenreg/greenreg.h:42,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/src/greenreg.cpp:35:
/usr/local/systemc-2.3.0/include/sysc/packages/boost/get_pointer.hpp:21:40: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
 template<class T> T * get_pointer(std::auto_ptr<T> const& p)
                                        ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from /usr/local/systemc-2.3.0/include/sysc/packages/boost/get_pointer.hpp:8,
                 from /usr/local/systemc-2.3.0/include/sysc/packages/boost/mem_fn.hpp:25,
                 from /usr/local/systemc-2.3.0/include/sysc/packages/boost/bind.hpp:26,
                 from /usr/local/systemc-2.3.0/include/sysc/kernel/sc_boost.h:44,
                 from /usr/local/systemc-2.3.0/include/sysc/kernel/sc_dynamic_processes.h:36,
                 from /usr/local/systemc-2.3.0/include/systemc:124,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/include/greenreg/sysc_ext/utils/gr_report.h:50,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/include/greenreg/greenreg.h:42,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/src/greenreg.cpp:35:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
In file included from /home/zhanglong/vp/libs/greenlib/greensocket/include/greensocket/generic/green_socket_extension_support_base.h:144:0,
                 from /home/zhanglong/vp/libs/greenlib/greensocket/include/greensocket/generic/green_socket_bind_checker.h:24,
                 from /home/zhanglong/vp/libs/greenlib/greensocket/include/greensocket/initiator/green_initiator_socket_base.h:28,
                 from /home/zhanglong/vp/libs/greenlib/greensocket/include/greensocket/initiator/single_socket.h:26,
                 from /home/zhanglong/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/generic_transaction.h:29,
                 from /home/zhanglong/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/GSGPSocket.h:32,
                 from /home/zhanglong/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/GSGPSlaveSocket.h:24,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/include/greenreg/framework/core/gr_common.h:53,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/include/greenreg/greenreg.h:45,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/src/greenreg.cpp:35:
/home/zhanglong/vp/libs/greenlib/greensocket/include/greensocket/generic/green_socket_extension_support_base.tpp: In static member function ‘static T* gs::socket::extension_support_base<TRAITS>::get_extension(const gs::ext::gs_data_id&, gs::socket::extension_support_base<TRAITS>::payload_type&)’:
/home/zhanglong/vp/libs/greenlib/greensocket/include/greensocket/generic/green_socket_extension_support_base.tpp:127:29: error: expected primary-expression before ‘>’ token
   T* tmp=txn.get_extension<T>(); //get the pointer
                             ^
/home/zhanglong/vp/libs/greenlib/greensocket/include/greensocket/generic/green_socket_extension_support_base.tpp:127:31: error: expected primary-expression before ‘)’ token
   T* tmp=txn.get_extension<T>(); //get the pointer
                               ^
In file included from /home/zhanglong/vp/libs/greenlib/greencontrol/include/greencontrol/config.h:50:0,
                 from /home/zhanglong/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/GSGPSocket.h:36,
                 from /home/zhanglong/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/GSGPSlaveSocket.h:24,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/include/greenreg/framework/core/gr_common.h:53,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/include/greenreg/greenreg.h:45,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/src/greenreg.cpp:35:
/home/zhanglong/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/GCnf_Api/cnf_api_if.h: At global scope:
/home/zhanglong/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/GCnf_Api/cnf_api_if.h:237:65: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   virtual sc_event& getUpdateEvent(const std::string &parname)  throw (RegisterObserverFailedException) = 0;
                                                                 ^~~~~
/home/zhanglong/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/GCnf_Api/cnf_api_if.h:325:40: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   virtual sc_event& getNewParamEvent() throw (RegisterObserverFailedException) = 0;
                                        ^~~~~
In file included from /home/zhanglong/vp/libs/greenlib/greencontrol/include/greencontrol/config.h:56:0,
                 from /home/zhanglong/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/GSGPSocket.h:36,
                 from /home/zhanglong/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/GSGPSlaveSocket.h:24,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/include/greenreg/framework/core/gr_common.h:53,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/include/greenreg/greenreg.h:45,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/src/greenreg.cpp:35:
/home/zhanglong/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/GCnf_Api/GCnf_Api_t.h:1013:57: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   sc_event& getUpdateEvent(const std::string &parname)  throw (RegisterObserverFailedException) {
                                                         ^~~~~
/home/zhanglong/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/GCnf_Api/GCnf_Api_t.h:1134:32: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   sc_event& getNewParamEvent() throw (RegisterObserverFailedException) {
                                ^~~~~
In file included from /home/zhanglong/vp/libs/greenlib/greencontrol/include/greencontrol/config.h:57:0,
                 from /home/zhanglong/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/GSGPSocket.h:36,
                 from /home/zhanglong/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/GSGPSlaveSocket.h:24,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/include/greenreg/framework/core/gr_common.h:53,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/include/greenreg/greenreg.h:45,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/src/greenreg.cpp:35:
/home/zhanglong/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/GCnf_private_Api/gcnf_private_api_t.h:486:59: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     sc_event& getUpdateEvent(const std::string &parname)  throw (RegisterObserverFailedException) {
                                                           ^~~~~
/home/zhanglong/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/GCnf_private_Api/gcnf_private_api_t.h:506:34: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     sc_event& getNewParamEvent() throw (RegisterObserverFailedException) {
                                  ^~~~~
In file included from /home/zhanglong/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/gs_param/gs_param_class.h:33:0,
                 from /home/zhanglong/vp/libs/greenlib/greencontrol/include/greencontrol/config.h:71,
                 from /home/zhanglong/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/GSGPSocket.h:36,
                 from /home/zhanglong/vp/libs/greenlib/gsgpsocket/include/gsgpsocket/transport/GSGPSlaveSocket.h:24,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/include/greenreg/framework/core/gr_common.h:53,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/include/greenreg/greenreg.h:45,
                 from /home/zhanglong/vp/libs/greenlib/greenreg/src/greenreg.cpp:35:
/home/zhanglong/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/gs_param/gs_param_native.hpp: In member function ‘gs::cnf::gs_param<bool>::my_type& gs::cnf::gs_param<bool>::operator++()’:
/home/zhanglong/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/gs_param/gs_param_operator_macros.h:79:7: warning: use of an operand of type ‘bool’ in ‘operator++’ is deprecated [-Wdeprecated]
     ++tmp_val;                                                       \
       ^
/home/zhanglong/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/gs_param/gs_param_native.hpp:261:3: note: in expansion of macro ‘GC_SPECIALISATIONS_INCREMENT_OPERATORS’
   GC_SPECIALISATIONS_INCREMENT_OPERATORS;
   ^
/home/zhanglong/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/gs_param/gs_param_native.hpp: In member function ‘gs::cnf::gs_param<bool>::val_type gs::cnf::gs_param<bool>::operator++(int)’:
/home/zhanglong/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/gs_param/gs_param_operator_macros.h:89:16: warning: use of an operand of type ‘bool’ in ‘operator++’ is deprecated [-Wdeprecated]
     tmp_set_val++;                                                   \
                ^
/home/zhanglong/vp/libs/greenlib/greencontrol/include/greencontrol/gcnf/apis/gs_param/gs_param_native.hpp:261:3: note: in expansion of macro ‘GC_SPECIALISATIONS_INCREMENT_OPERATORS’
   GC_SPECIALISATIONS_INCREMENT_OPERATORS;
   ^
libs/greenlib/greenreg/lib/CMakeFiles/greenreg.dir/build.make:62: recipe for target 'libs/greenlib/greenreg/lib/CMakeFiles/greenreg.dir/__/src/greenreg.cpp.o' failed
make[2]: *** [libs/greenlib/greenreg/lib/CMakeFiles/greenreg.dir/__/src/greenreg.cpp.o] Error 1
CMakeFiles/Makefile2:1810: recipe for target 'libs/greenlib/greenreg/lib/CMakeFiles/greenreg.dir/all' failed
make[1]: *** [libs/greenlib/greenreg/lib/CMakeFiles/greenreg.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by long-a-zhang-tieto** [comment]
I use the docker then it's good.

**Comment by nicolast0604** [comment]
I met the same issue. Can anyone help?

**Comment by long771** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我是龙欣荣，很高兴收到您的邮件，我将尽快处理。
