### ISSUE TITLE
when will the compiler supporting nv_small be released?

### ISSUE THREAD

**Issue by LpengPC** [nvdla/sw#136]

**Comment by davide-giri** [comment]
Hi, is there a new estimate for the release date? Thanks!

**Comment by prasshantg** [comment]
@davide-giri @LpengPC we released nv_small support today, please check latest release and submit your feedback. Appreciate your patience and support.

**Comment by mmaciag** [comment]
@prasshantg This is great news. Thank you!

**Comment by shgoupf** [comment]
@prasshantg Great news, thanks!

**Comment by VVViy** [comment]
@prasshantg Finally! Thank you very much for this great news!
