### ISSUE TITLE
CROSS_COMPILE

### ISSUE THREAD

**Issue by unlimt** [nvdla/sw#14]
In "Building the Linux KMD" section, it says
make KDIR=<path_to_Linux_source> ARCH=arm64 CROSS_COMPILE=<path_to_toolchain>

Does anyone know what is the CROSS_COMPILE name and path ?
Thanks a lot for help !

**Comment by prasshantg** [comment]
It is path to arm64 toolchain for example Linaro toolchain for aarch64.

**Comment by arcbbb** [comment]
For your information, you can download it from `https://releases.linaro.org/components/toolchain/binaries/latest/aarch64-linux-gnu/`, and then for example,  set  `export CROSS_COMPILE=gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin`.

**Comment by unlimt** [comment]
Thanks for all feedback. I use the toolchain to build umd first. But I have a error:  

![umd_fail_2018-0118](https://user-images.githubusercontent.com/35524658/35091439-a7e53c88-fc77-11e7-9428-c3ff3b72b5b0.png)

Does anyone know how to fix it ?
Thank you very much !

**Comment by HKLee2040** [comment]
@unlimt I didn't build umd by myself, but I met isnan issue before.

https://github.com/nvdla/hw/issues/69

jarodw0723 suggest that:
"What is your glibc version (ldd --version will show)? With glibc >= 2.23 this could be an issue, and replace 'isnan' with 'std::isnan' indeed will fix it."

Maybe you can try it.

**Comment by prasshantg** [comment]
@unlimt do you still observe this issue?

**Comment by yirs2001** [comment]
@unlimt , I did both (kmd, umd) OK.
The following are my steps:
umd:
1.  export TOP=/home/willyi/nvdla/sw/umd 
2.  export TOOLCHAIN_PREFIX==/home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu- 
3. go nvdla/sw/umd folder and issue make
The following is my log:
willyi@mantis-HP-EliteDesk-800-G1-TWR:~/nvdla/sw/umd$ make
for dir in core/runtime tests/runtime; do \
                make -C $dir; \
        done
MODULE_CC /home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc
make[1]: Entering directory `/home/willyi/nvdla/sw/umd/core/runtime'
compiling /home/willyi/nvdla/sw/umd/core/common/ErrorLogging.c
/home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc -Os -g -fPIC -finline -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration --std=c99 -DNVDLA_UTILS_ERROR_TAG="\"DLA_RUNTIME\""   -I/home/willyi/nvdla/sw/umd/include -I/home/willyi/nvdla/sw/umd/core/include -I/home/willyi/nvdla/sw/umd/core/common/include -I/home/willyi/nvdla/sw/umd/port/linux/include -I/home/willyi/nvdla/sw/umd/external/include -I./include -I. -c /home/willyi/nvdla/sw/umd/core/common/ErrorLogging.c -MD -MT /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/core/common/ErrorLogging.o -MF /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/core/common/ErrorLogging.d -o /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/core/common/ErrorLogging.o
compiling /home/willyi/nvdla/sw/umd/port/linux/nvdla.c
/home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc -Os -g -fPIC -finline -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration --std=c99 -DNVDLA_UTILS_ERROR_TAG="\"DLA_RUNTIME\""   -I/home/willyi/nvdla/sw/umd/include -I/home/willyi/nvdla/sw/umd/core/include -I/home/willyi/nvdla/sw/umd/core/common/include -I/home/willyi/nvdla/sw/umd/port/linux/include -I/home/willyi/nvdla/sw/umd/external/include -I./include -I. -c /home/willyi/nvdla/sw/umd/port/linux/nvdla.c -MD -MT /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/port/linux/nvdla.o -MF /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/port/linux/nvdla.d -o /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/port/linux/nvdla.o
compiling /home/willyi/nvdla/sw/umd/port/linux/nvdla_os.c
/home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc -Os -g -fPIC -finline -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration --std=c99 -DNVDLA_UTILS_ERROR_TAG="\"DLA_RUNTIME\""   -I/home/willyi/nvdla/sw/umd/include -I/home/willyi/nvdla/sw/umd/core/include -I/home/willyi/nvdla/sw/umd/core/common/include -I/home/willyi/nvdla/sw/umd/port/linux/include -I/home/willyi/nvdla/sw/umd/external/include -I./include -I. -c /home/willyi/nvdla/sw/umd/port/linux/nvdla_os.c -MD -MT /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/port/linux/nvdla_os.o -MF /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/port/linux/nvdla_os.d -o /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/port/linux/nvdla_os.o
compiling /home/willyi/nvdla/sw/umd/core/common/Check.cpp
/home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc -Os -g -fPIC -finline -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration --std=c++11 -fexceptions -fno-rtti -DNVDLA_UTILS_ERROR_TAG="\"DLA_RUNTIME\""  -I/home/willyi/nvdla/sw/umd/include -I/home/willyi/nvdla/sw/umd/core/include -I/home/willyi/nvdla/sw/umd/core/common/include -I/home/willyi/nvdla/sw/umd/port/linux/include -I/home/willyi/nvdla/sw/umd/external/include -I./include -I.  -c /home/willyi/nvdla/sw/umd/core/common/Check.cpp -MD -MT /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/core/common/Check.o -MF /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/core/common/Check.d -o /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/core/common/Check.o
compiling /home/willyi/nvdla/sw/umd/core/common/EMUInterface.cpp
/home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc -Os -g -fPIC -finline -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration --std=c++11 -fexceptions -fno-rtti -DNVDLA_UTILS_ERROR_TAG="\"DLA_RUNTIME\""  -I/home/willyi/nvdla/sw/umd/include -I/home/willyi/nvdla/sw/umd/core/include -I/home/willyi/nvdla/sw/umd/core/common/include -I/home/willyi/nvdla/sw/umd/port/linux/include -I/home/willyi/nvdla/sw/umd/external/include -I./include -I.  -c /home/willyi/nvdla/sw/umd/core/common/EMUInterface.cpp -MD -MT /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/core/common/EMUInterface.o -MF /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/core/common/EMUInterface.d -o /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/core/common/EMUInterface.o
compiling /home/willyi/nvdla/sw/umd/core/common/EMUInterfaceA.cpp
/home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc -Os -g -fPIC -finline -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration --std=c++11 -fexceptions -fno-rtti -DNVDLA_UTILS_ERROR_TAG="\"DLA_RUNTIME\""  -I/home/willyi/nvdla/sw/umd/include -I/home/willyi/nvdla/sw/umd/core/include -I/home/willyi/nvdla/sw/umd/core/common/include -I/home/willyi/nvdla/sw/umd/port/linux/include -I/home/willyi/nvdla/sw/umd/external/include -I./include -I.  -c /home/willyi/nvdla/sw/umd/core/common/EMUInterfaceA.cpp -MD -MT /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/core/common/EMUInterfaceA.o -MF /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/core/common/EMUInterfaceA.d -o /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/core/common/EMUInterfaceA.o
compiling /home/willyi/nvdla/sw/umd/core/common/Loadable.cpp
/home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc -Os -g -fPIC -finline -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration --std=c++11 -fexceptions -fno-rtti -DNVDLA_UTILS_ERROR_TAG="\"DLA_RUNTIME\""  -I/home/willyi/nvdla/sw/umd/include -I/home/willyi/nvdla/sw/umd/core/include -I/home/willyi/nvdla/sw/umd/core/common/include -I/home/willyi/nvdla/sw/umd/port/linux/include -I/home/willyi/nvdla/sw/umd/external/include -I./include -I.  -c /home/willyi/nvdla/sw/umd/core/common/Loadable.cpp -MD -MT /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/core/common/Loadable.o -MF /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/core/common/Loadable.d -o /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/core/common/Loadable.o
compiling Emulator.cpp
/home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc -Os -g -fPIC -finline -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration --std=c++11 -fexceptions -fno-rtti -DNVDLA_UTILS_ERROR_TAG="\"DLA_RUNTIME\""  -I/home/willyi/nvdla/sw/umd/include -I/home/willyi/nvdla/sw/umd/core/include -I/home/willyi/nvdla/sw/umd/core/common/include -I/home/willyi/nvdla/sw/umd/port/linux/include -I/home/willyi/nvdla/sw/umd/external/include -I./include -I.  -c Emulator.cpp -MD -MT /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime/Emulator.o -MF /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime/Emulator.d -o /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime/Emulator.o
compiling Runtime.cpp
/home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc -Os -g -fPIC -finline -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration --std=c++11 -fexceptions -fno-rtti -DNVDLA_UTILS_ERROR_TAG="\"DLA_RUNTIME\""  -I/home/willyi/nvdla/sw/umd/include -I/home/willyi/nvdla/sw/umd/core/include -I/home/willyi/nvdla/sw/umd/core/common/include -I/home/willyi/nvdla/sw/umd/port/linux/include -I/home/willyi/nvdla/sw/umd/external/include -I./include -I.  -c Runtime.cpp -MD -MT /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime/Runtime.o -MF /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime/Runtime.d -o /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime/Runtime.o
linking /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime/libnvdla_runtime.mod.o
/home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-ld -r /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/core/common/ErrorLogging.o /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/port/linux/nvdla.o /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/port/linux/nvdla_os.o /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/core/common/Check.o /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/core/common/EMUInterface.o /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/core/common/EMUInterfaceA.o /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime//home/willyi/nvdla/sw/umd/core/common/Loadable.o /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime/Emulator.o /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime/Runtime.o -o /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime/libnvdla_runtime.mod.o
building /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime/libnvdla_runtime.so
/home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++ -shared /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime/libnvdla_runtime.mod.o -o /home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime/libnvdla_runtime.so
make[1]: Leaving directory `/home/willyi/nvdla/sw/umd/core/runtime'
MODULE_CC /home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc
make[1]: Entering directory `/home/willyi/nvdla/sw/umd/tests/runtime'
compiling DlaImage.cpp
/home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc  -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration -DNVDLA_UTILS_ERROR_TAG="\"DLA_TEST\""  -I/home/willyi/nvdla/sw/umd/include -I/home/willyi/nvdla/sw/umd/core/include -I/home/willyi/nvdla/sw/umd/external/include -I/home/willyi/nvdla/sw/umd/external/libjpeg-turbo -I./include -I.  -c DlaImage.cpp -MD -MT /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/DlaImage.o -MF /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/DlaImage.d -o /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/DlaImage.o
compiling DlaImageUtils.cpp
/home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc  -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration -DNVDLA_UTILS_ERROR_TAG="\"DLA_TEST\""  -I/home/willyi/nvdla/sw/umd/include -I/home/willyi/nvdla/sw/umd/core/include -I/home/willyi/nvdla/sw/umd/external/include -I/home/willyi/nvdla/sw/umd/external/libjpeg-turbo -I./include -I.  -c DlaImageUtils.cpp -MD -MT /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/DlaImageUtils.o -MF /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/DlaImageUtils.d -o /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/DlaImageUtils.o
compiling Server.cpp
/home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc  -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration -DNVDLA_UTILS_ERROR_TAG="\"DLA_TEST\""  -I/home/willyi/nvdla/sw/umd/include -I/home/willyi/nvdla/sw/umd/core/include -I/home/willyi/nvdla/sw/umd/external/include -I/home/willyi/nvdla/sw/umd/external/libjpeg-turbo -I./include -I.  -c Server.cpp -MD -MT /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/Server.o -MF /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/Server.d -o /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/Server.o
compiling RuntimeTest.cpp
/home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc  -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration -DNVDLA_UTILS_ERROR_TAG="\"DLA_TEST\""  -I/home/willyi/nvdla/sw/umd/include -I/home/willyi/nvdla/sw/umd/core/include -I/home/willyi/nvdla/sw/umd/external/include -I/home/willyi/nvdla/sw/umd/external/libjpeg-turbo -I./include -I.  -c RuntimeTest.cpp -MD -MT /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/RuntimeTest.o -MF /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/RuntimeTest.d -o /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/RuntimeTest.o
compiling TestUtils.cpp
/home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc  -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration -DNVDLA_UTILS_ERROR_TAG="\"DLA_TEST\""  -I/home/willyi/nvdla/sw/umd/include -I/home/willyi/nvdla/sw/umd/core/include -I/home/willyi/nvdla/sw/umd/external/include -I/home/willyi/nvdla/sw/umd/external/libjpeg-turbo -I./include -I.  -c TestUtils.cpp -MD -MT /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/TestUtils.o -MF /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/TestUtils.d -o /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/TestUtils.o
compiling main.cpp
/home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc  -W -Wall -Wno-multichar -Wno-unused-parameter -Wno-unused-function -Werror-implicit-function-declaration -DNVDLA_UTILS_ERROR_TAG="\"DLA_TEST\""  -I/home/willyi/nvdla/sw/umd/include -I/home/willyi/nvdla/sw/umd/core/include -I/home/willyi/nvdla/sw/umd/external/include -I/home/willyi/nvdla/sw/umd/external/libjpeg-turbo -I./include -I.  -c main.cpp -MD -MT /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/main.o -MF /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/main.d -o /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/main.o
linking /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/nvdla_runtime.mod.o
/home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-ld -r /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/DlaImage.o /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/DlaImageUtils.o /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/Server.o /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/RuntimeTest.o /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/TestUtils.o /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/main.o -o /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/nvdla_runtime.mod.o
building /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/nvdla_runtime
/home/willyi/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++ /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/nvdla_runtime.mod.o -pthread -L/home/willyi/nvdla/sw/umd/external/ -ljpeg -L/home/willyi/nvdla/sw/umd/out/runtime/libnvdla_runtime -lnvdla_runtime -o /home/willyi/nvdla/sw/umd/out/runtime/nvdla_runtime/nvdla_runtime
make[1]: Leaving directory `/home/willyi/nvdla/sw/umd/tests/runtime'

kmd:
1. download linux-4.14.3 kernel source
2.  In kmd folder, issue make KDIR=~/linux-4.13.3 ARCH=arm64 CROSS_COMPILE=~/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-
The following is my log:
willyi@mantis-HP-EliteDesk-800-G1-TWR:~/nvdla/sw/kmd$ make KDIR=~/linux-4.13.3 ARCH=arm64 CROSS_COMPILE=~/gcc-linaro-7.2.1-2017.11-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-
make -C /home/willyi/linux-4.13.3 M=$PWD modules
make[1]: Entering directory `/home/willyi/linux-4.13.3'
  CC [M]  /home/willyi/nvdla/sw/kmd/port/linux/../../firmware/scheduler.o
  CC [M]  /home/willyi/nvdla/sw/kmd/port/linux/../../firmware/engine.o
  CC [M]  /home/willyi/nvdla/sw/kmd/port/linux/../../firmware/bdma.o
  CC [M]  /home/willyi/nvdla/sw/kmd/port/linux/../../firmware/conv.o
  CC [M]  /home/willyi/nvdla/sw/kmd/port/linux/../../firmware/sdp.o
  CC [M]  /home/willyi/nvdla/sw/kmd/port/linux/../../firmware/cdp.o
  CC [M]  /home/willyi/nvdla/sw/kmd/port/linux/../../firmware/pdp.o
  CC [M]  /home/willyi/nvdla/sw/kmd/port/linux/../../firmware/rubik.o
  CC [M]  /home/willyi/nvdla/sw/kmd/port/linux/../../firmware/cache.o
  CC [M]  /home/willyi/nvdla/sw/kmd/port/linux/../../firmware/common.o
  CC [M]  /home/willyi/nvdla/sw/kmd/port/linux/../../firmware/engine_data.o
  CC [M]  /home/willyi/nvdla/sw/kmd/port/linux/../../firmware/engine_isr.o
  CC [M]  /home/willyi/nvdla/sw/kmd/port/linux/../../firmware/engine_debug.o
  CC [M]  /home/willyi/nvdla/sw/kmd/port/linux/nvdla_core_callbacks.o
  CC [M]  /home/willyi/nvdla/sw/kmd/port/linux/nvdla_gem.o
  LD [M]  /home/willyi/nvdla/sw/kmd/port/linux/opendla.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/willyi/nvdla/sw/kmd/port/linux/opendla.mod.o
  LD [M]  /home/willyi/nvdla/sw/kmd/port/linux/opendla.ko
make[1]: Leaving directory `/home/willyi/linux-4.13.3'

Hope it's helpful for you.

**Comment by prasshantg** [comment]
@unlimt sorry for the delay, Can you try with steps mentioned at http://nvdla.org/vp.html#building-linux-kernel-for-nvdla-virtual-simulator ?

**Comment by sivagururaman** [comment]
@prasshantg 
I tried with the steps mentioned at the site : http://nvdla.org/vp.html#building-linux-kernel-for-nvdla-virtual-simulator  and also the steps mentioned by @unlimt. While UMD built for me, KMD did not.
It gave exactly the same issue(s)
make[1]: Leaving directory '/home/linux'
Makefile:33: recipe for target 'modules' failed
make: *** [modules] Error 2

Can you please help me with this issue? How do I build kmd?

Thanks!

**Comment by sivagururaman** [comment]
I resorted to using the built kernel and could build KMD post that. I am now using the version mentioned in the link http://nvdla.org/vp.html#building-linux-kernel-for-nvdla-virtual-simulator  in the comand line for KMD build.  Working for me. Thanks!

**Comment by prasshantg** [comment]
@silvaurus could you please help with how did you resolve #51 ? Same steps can be useful for @sivagururaman

**Comment by prasshantg** [comment]
Issue resolved in #51
