### ISSUE TITLE
new nvdla_runtime error

### ISSUE THREAD

**Issue by Hong-333** [nvdla/sw#140]
i got new nvdla sw folder and run nvdla_runtime for vp
but i failed
please check my log 

-insmod opendla_1.ko
# ./nvdla_runtime --loadable ../../regression/flatbufs/kmd/CONV/CONV_D_L0_0_smal
l_fbuf 
creating new runtime context...
Emulator starting
submitting tasks...
[  103.945452] Enter:dla_read_network_config
[  103.945973] Exit:dla_read_network_config status=0
[  103.946064] Enter: dla_initiate_processors
[  103.946253] Enter: dla_submit_operation
[  103.946340] Prepare Convolution operation index 0 ROI 0 dep_count 1
[  103.946438] Enter: dla_prepare_operation
[  103.946678] processor:Convolution group:0, rdma_group:0 available
[  103.946828] Enter: dla_read_config
[  103.947026] Exit: dla_read_config
[  103.947181] Exit: dla_prepare_operation status=0
[  103.947382] Enter: dla_program_operation
[  103.947540] Program Convolution operation index 0 ROI 0 Group[0]

Fatal: cmac_a_reg_model.cpp: 24:Failed to decode NVDLA_CMAC_A register write with w_mask at offset 0x10, data 0x00000000
In file: ../cmod/cmac/gen/cmac_a_reg_model.cpp:24
In process: CPU.do_io @ 103900 ms
Aborted (core dumped)

-insmod opendla_2.ko
# ./nvdla_runtime --loadable ../../regression/flatbufs/kmd/CONV/CONV_D_L0_0_smal
l_fbuf 
creating new runtime context...
Emulator starting
submitting tasks...
[   39.186591] Enter:dla_read_network_config
[   39.187058] Exit:dla_read_network_config status=0
[   39.187141] Enter: dla_initiate_processors
[   39.187325] Enter: dla_submit_operation
[   39.187395] Prepare Convolution operation index 0 ROI 0 dep_count 1
[   39.187490] Enter: dla_prepare_operation
[   39.187720] processor:Convolution group:0, rdma_group:0 available
[   39.187838] Enter: dla_read_config
[   39.188041] Exit: dla_read_config
[   39.188125] Exit: dla_prepare_operation status=0
[   39.188228] Enter: dla_program_operation
[   39.188308] Program Convolution operation index 0 ROI 0 Group[0]
[   39.189897] no desc get due to index==-1
[   39.189989] no desc get due to index==-1
[   39.192420] no desc get due to index==-1
[   39.192520] no desc get due to index==-1
[   39.192592] no desc get due to index==-1
[   39.192670] no desc get due to index==-1
[   39.192748] Enter: dla_op_programmed
[   39.192868] Update dependency operation index 1 ROI 0 DEP_COUNT=1
[   39.192980] enable SDP in dla_update_dependency as depdency are resolved
[   39.193095] Enter: dla_enable_operation
[   39.193176] exit dla_enable_operation without actual enable due to processor hasn't been programmed
[   39.193369] Exit: dla_enable_operation status=0
[   39.193472] Exit: dla_op_programmed
[   39.193543] Exit: dla_program_operation status=0
[   39.193638] Exit: dla_submit_operation
[   39.193758] Enter: dla_dequeue_operation
[   39.193845] exit Convolution as there's no further operation
[   39.193946] Exit: dla_dequeue_operation
[   39.196366] Enter: dla_submit_operation
[   39.196462] Prepare SDP operation index 1 ROI 0 dep_count 0
[   39.196554] Enter: dla_prepare_operation
[   39.197403] processor:SDP group:0, rdma_group:0 available
[   39.197488] Enter: dla_read_config
[   39.197667] Exit: dla_read_config
[   39.197742] Exit: dla_prepare_operation status=0
[   39.197840] Enter: dla_program_operation
[   39.197913] Program SDP operation index 1 ROI 0 Group[0]
[   39.200179] no desc get due to index==-1
[   39.200292] no desc get due to index==-1
[   39.200367] no desc get due to index==-1
[   39.200440] no desc get due to index==-1
[   39.200513] no desc get due to index==-1
[   39.200583] no desc get due to index==-1
[   39.200662] Enter: dla_op_programmed
[   39.200730] Exit: dla_op_programmed
[   39.200797] Exit: dla_program_operation status=0
[   39.200883] Enter: dla_enable_operation
[   39.200978] Enable SDP operation index 1 ROI 0
[   39.201126] Enter: dla_op_enabled
[   39.201197] Update dependency operation index 0 ROI 0 DEP_COUNT=1
[   39.201305] enable Convolution in dla_update_dependency as depdency are resolved
[   39.201425] Enter: dla_enable_operation
[   39.201494] Enable Convolution operation index 0 ROI 0
[   39.201919] Enter: dla_op_enabled
[   39.201989] Exit: dla_op_enabled
[   39.204475] Exit: dla_enable_operation status=0
[   39.204580] Exit: dla_op_enabled
[   39.204643] Exit: dla_enable_operation status=0
[   39.204723] Exit: dla_submit_operation
[   39.204795] Enter: dla_dequeue_operation
[   39.204869] exit SDP as there's no further operation
[   39.204955] Exit: dla_dequeue_operation
[   39.205031] Exit: dla_initiate_processors status=0

Fatal: NV_NVDLA_cdma.cpp: 1283:NV_NVDLA_cdma::DirectConvDataResponseSequencerCommon, invalid configuration cdma_entries_, set value is 0x7F, it shall be 0x1FFF.
In file: ../cmod/cdma/NV_NVDLA_cdma.cpp:1283
In process: nvdla.nvdla_core.nvdla_core.cdma.ActDataReadResponseSequenceThread @ 39300 ms
Aborted (core dumped)

thank you

**Comment by prasshantg** [comment]
@Hong-333 is it with latest release? Please do not run unit tests. You can try some resnet-50 using nvdla compiler.

**Comment by kanghanbich** [comment]
> @Hong-333 is it with latest release? Please do not run unit tests. You can try some resnet-50 using nvdla compiler.

hi, I went to MNIST, not unit test, and I received the same message.

**Fatal: cmac_a_reg_model.cpp: 24:Failed to decode NVDLA_CMAC_A register write with w_mask at offset 0x10, data 0x00000000**

As far as I know, there's no offset 0x10 in the MAC_A register, then can't there be an mnist?

**Comment by prasshantg** [comment]
Is that model compiled using latest compiler release?

https://github.com/nvdla/sw/blob/master/prebuilt/linux/nvdla_compiler

**Comment by Hong-333** [comment]
> Is that model compiled using latest compiler release?
> 
> https://github.com/nvdla/sw/blob/master/prebuilt/linux/nvdla_compiler

yes i used latest compiler resnet-18 but i failed too

./nvdla_compiler --configtarget nv_small --caffemodel ../../resnet-18.caffemodel --prototxt ../../ResNet-18-deploy.prototxt 
creating new wisdom context...
opening wisdom context...
parsing caffe network...
libnvdla<3> mark prob
Marking total 1 outputs
attaching parsed network to the wisdom...
compiling profile "fast-math"... config "nv_small"...
closing wisdom context...


# ./nvdla_runtime --loadable ../../../../prebuilt/linux/resnet_fast_math.nvdla   --i
mage ../../../../m01440764_96.jpg 
creating new runtime context...
Emulator starting
dlaimg height: 224 x 224 x 3: LS: 1792 SS: 0 Size: 401408
(DLA_TEST) Error 0x00000002: Unsupported (pixel, data) combination: (37, 2) (in TestUtils.cpp, function createImageCopy(), line 190)
(DLA_TEST) Error 0x00000002: (propagating from RuntimeTest.cpp, function copyImageToInputTensor(), line 100)
(DLA_TEST) Error 0x00000002: (propagating from RuntimeTest.cpp, function setupInputBuffer(), line 162)
(DLA_TEST) Error 0x00000002: (propagating from RuntimeTest.cpp, function runTest(), line 382)
(DLA_TEST) Error 0x00000002: (propagating from RuntimeTest.cpp, function run(), line 440)
Shutdown signal received, exiting
(DLA_TEST) Error 0x00000002: (propagating from main.cpp, function launchTest(), line 87)

**Comment by prasshantg** [comment]
nv_small is INT8 only. You need to give arguments for int8 compilation i.e. calibtable and quantization mode

Usage: ./nvdla_compiler [-options] --prototxt <prototxt_file> --caffemodel <caffemodel_file>
where options include:
    -h                                                 print this help message
    -o <outputpath>                                    outputs wisdom files in 'outputpath' directory
    --profile <basic|default|performance|fast-math>    computation profile(fast-math by default)
    --cprecision <fp16|int8>                           compute precision(fp16 by default)
    --configtarget <nv_full|nv_large|nv_small>         target platform(opendla-full by default)
    --calibtable <int8 calib file>                     calibration table for INT8 networks
    --quantizationMode <per-kernel|per-filter>         quantization mode for INT8(per-kernel by default)

More details about calibtable are at https://github.com/nvdla/sw/blob/master/LowPrecision.md

**Comment by Hong-333** [comment]
> nv_small is INT8 only. You need to give arguments for int8 compilation i.e. calibtable and quantization mode
> 
> Usage: ./nvdla_compiler [-options] --prototxt <prototxt_file> --caffemodel <caffemodel_file>
> where options include:
> -h print this help message
> -o outputs wisdom files in 'outputpath' directory
> --profile <basic|default|performance|fast-math> computation profile(fast-math by default)
> --cprecision <fp16|int8> compute precision(fp16 by default)
> --configtarget <nv_full|nv_large|nv_small> target platform(opendla-full by default)
> --calibtable calibration table for INT8 networks
> --quantizationMode <per-kernel|per-filter> quantization mode for INT8(per-kernel by default)
> 
> More details about calibtable are at https://github.com/nvdla/sw/blob/master/LowPrecision.md

please could you give me an example file?

**Comment by kanghanbich** [comment]
**./nvdla_compiler --configtarget nv_small --cprecision int8 --caffemodel lenet_itro_10000.caffemodel --prototxt lenet.prototxt**

I set the options like this.

Are you saying that you need to compile more options here?
--calibtable calibration table for INT8 networks
--quantizationMode <per-kernel|per-filter> quantization mode for INT8(per-kernel by default)


Could you please show me the file of the file or table?
I think you've tried the resnet-50. Please give me the file.
 don't know how to give the option.

**Comment by Hong-333** [comment]
#i made it for mnist like this 
{
	"data" : {
		"scale": 0.00781453,
		"min": 0,
		"max": 0,
		"offset": 0
	},
	"conv1" : {
		"scale": 0.0891214,
		"min": 0,
		"max": 0,
		"offset": 0
	},
	"pool1" : {
		"scale": 0.0891214,
		"min": 0,
		"max": 0,
		"offset": 0
	},
	"conv2" : {
		"scale": 0.0891214,
		"min": 0,
		"max": 0,
		"offset": 0
	},
	"pool2" : {
		"scale": 0.0891214,
		"min": 0,
		"max": 0,
		"offset": 0
	},
	"ip1" : {
		"scale": 0.0891214,
		"min": 0,
		"max": 0,
		"offset": 0
	},
	"ip2" : {
		"scale": 0.0891214,
		"min": 0,
		"max": 0,
		"offset": 0
	},
}

is that right??

parsing calibration table...
(DLA) Error 0x00000004: JSON parsing error: Missing a name for object member. (in ParseTest.cpp, function parseTensorScales(), line 53)
(DLA) Error 0x00000004: (propagating from ParseTest.cpp, function parseCaffeNetwork(), line 157)
(DLA) Error 0x00000004: (propagating from ParseTest.cpp, function parseAndCompile(), line 230)
(DLA) Error 0x00000004: (propagating from main.cpp, function launchTest(), line 96)

**Comment by Hong-333** [comment]
#i made it for mnist like this 

{
	"data" : {
		"scale": 0.00781453,
		"min": 0,
		"max": 0,
		"offset": 0
	},
	"conv1" : {
		"scale": 0.0891214,
		"min": 0,
		"max": 0,
		"offset": 0
	},
	"pool1" : {
		"scale": 0.0891214,
		"min": 0,
		"max": 0,
		"offset": 0
	},
	"conv2" : {
		"scale": 0.0891214,
		"min": 0,
		"max": 0,
		"offset": 0
	},
	"pool2" : {
		"scale": 0.0891214,
		"min": 0,
		"max": 0,
		"offset": 0
	},
	"ip1" : {
		"scale": 0.0891214,
		"min": 0,
		"max": 0,
		"offset": 0
	},
	"ip2" : {
		"scale": 0.0891214,
		"min": 0,
		"max": 0,
		"offset": 0
	}
} 

but i got error 

./nvdla_compiler --caffemodel ../../lenet_iter_10000.caffemodel --prototxt ../../mnist.prototxt --cprecision int8 --configtarget nv_small --calibtable ../../calib.json 
creating new wisdom context...
opening wisdom context...
parsing caffe network...
libnvdla<3> mark prob
Marking total 1 outputs
parsing calibration table...
nvdla_compiler: /home/isharif/OpenDLA/internal/dla-open/umd/external/include/rapidjson/document.h:1105: rapidjson::GenericValue<Encoding, Allocator>& rapidjson::GenericValue<Encoding, Allocator>::operator[](const rapidjson::GenericValue<Encoding, SourceAllocator>&) [with SourceAllocator = rapidjson::MemoryPoolAllocator<>; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>]: Assertion `false' failed.
Aborted (core dumped)

**Comment by prasshantg** [comment]
Let me share you the sample calibration table, give me a day.

**Comment by Hong-333** [comment]
> Let me share you the sample calibration table, give me a day.

thank you sir I'll be waiting

**Comment by prasshantg** [comment]
@Hong-333 some layers are missing in your calib table. And please use opendla_2.ko for nv_small and nv_large. opendla_1.ko is for nv_full.

{
        "data" : {
                "scale": 0.00781453,
                "min": 0,
                "max": 0,
                "offset": 0
        },
        "scale" : {
                "scale": 0.00781453,
                "min": 0,
                "max": 0,
                "offset": 0
        },
        "conv1" : {
                "scale": 0.0891214,
                "min": 0,
                "max": 0,
                "offset": 0
        },
        "pool1" : {
                "scale": 0.0891214,
                "min": 0,
                "max": 0,
                "offset": 0
        },
        "conv2" : {
                "scale": 0.0891214,
                "min": 0,
                "max": 0,
                "offset": 0
        },
        "pool2" : {
                "scale": 0.0891214,
                "min": 0,
                "max": 0,
                "offset": 0
        },
        "ip1" : {
                "scale": 0.0891214,
                "min": 0,
                "max": 0,
                "offset": 0
        },
        "relu1" : {
                "scale": 0.0891214,
                "min": 0,
                "max": 0,
                "offset": 0
        },
        "ip2" : {
                "scale": 0.0891214,
                "min": 0,
                "max": 0,
                "offset": 0
        },
        "prob" : {
                "scale": 0.0891214,
                "min": 0,
                "max": 0,
                "offset": 0
        }
}

**Comment by kanghanbich** [comment]
Hi! I executed nv_small safely with the table information you provided me.
By the way, can you tell me how to get the value of scale?
I don't know how to set that value.

Thank you for your help.

**Comment by kanghanbich** [comment]
> @Hong-333 some layers are missing in your calib table. And please use opendla_2.ko for nv_small and nv_large. opendla_1.ko is for nv_full.
> 
> {
> "data" : {
> "scale": 0.00781453,
> "min": 0,
> "max": 0,
> "offset": 0
> },
> "scale" : {
> "scale": 0.00781453,
> "min": 0,
> "max": 0,
> "offset": 0
> },
> "conv1" : {
> "scale": 0.0891214,
> "min": 0,
> "max": 0,
> "offset": 0
> },
> "pool1" : {
> "scale": 0.0891214,
> "min": 0,
> "max": 0,
> "offset": 0
> },
> "conv2" : {
> "scale": 0.0891214,
> "min": 0,
> "max": 0,
> "offset": 0
> },
> "pool2" : {
> "scale": 0.0891214,
> "min": 0,
> "max": 0,
> "offset": 0
> },
> "ip1" : {
> "scale": 0.0891214,
> "min": 0,
> "max": 0,
> "offset": 0
> },
> "relu1" : {
> "scale": 0.0891214,
> "min": 0,
> "max": 0,
> "offset": 0
> },
> "ip2" : {
> "scale": 0.0891214,
> "min": 0,
> "max": 0,
> "offset": 0
> },
> "prob" : {
> "scale": 0.0891214,
> "min": 0,
> "max": 0,
> "offset": 0
> }
> }

Hi! I executed nv_small safely with the table information you provided me.
By the way, can you tell me how to get the value of scale?
I don't know how to set that value.

Thank you for your help.

**Comment by Hong-333** [comment]
> @Hong-333 some layers are missing in your calib table. And please use opendla_2.ko for nv_small and nv_large. opendla_1.ko is for nv_full.
> 
> {
> "data" : {
> "scale": 0.00781453,
> "min": 0,
> "max": 0,
> "offset": 0
> },
> "scale" : {
> "scale": 0.00781453,
> "min": 0,
> "max": 0,
> "offset": 0
> },
> "conv1" : {
> "scale": 0.0891214,
> "min": 0,
> "max": 0,
> "offset": 0
> },
> "pool1" : {
> "scale": 0.0891214,
> "min": 0,
> "max": 0,
> "offset": 0
> },
> "conv2" : {
> "scale": 0.0891214,
> "min": 0,
> "max": 0,
> "offset": 0
> },
> "pool2" : {
> "scale": 0.0891214,
> "min": 0,
> "max": 0,
> "offset": 0
> },
> "ip1" : {
> "scale": 0.0891214,
> "min": 0,
> "max": 0,
> "offset": 0
> },
> "relu1" : {
> "scale": 0.0891214,
> "min": 0,
> "max": 0,
> "offset": 0
> },
> "ip2" : {
> "scale": 0.0891214,
> "min": 0,
> "max": 0,
> "offset": 0
> },
> "prob" : {
> "scale": 0.0891214,
> "min": 0,
> "max": 0,
> "offset": 0
> }
> }

thank you for your reply
I succeeded in compiling MNIST 
I run nvdla_runtime with compiled file
but output result is not correct (3 0 3 0 0 0 0 0 0 4 0)
(0 0 0 0 0 0 0 0 1 0) is the right answer for me
I think i need to write the value of the calib table correctly
i read this file https://github.com/nvdla/sw/blob/master/LowPrecision.md
but i don't know calculate the scale value
How do I calculate the scale value 

I'm sorry to keep asking. :(

**Comment by prasshantg** [comment]
@Hong-333 @kanghanbich glad that you are able to run the model. To get the correct calibration table, you need to gather dynamic range information for each tensor in layer and then calculate scale factor using source and target dynamic range.

Most of the time results vary depending on what source dynamic range you select. It decides resolution and hence how much would be the data loss after quantization.

**Comment by prasshantg** [comment]
@Hong-333 @kanghanbich  Do you need more information? Can we close this issue if it is working fine for you?

**Comment by kanghanbich** [comment]
No more questions. Thank you.

**Comment by gitosu67** [comment]
Hi, @Hong-333 @prasshantg can you share the files for mnist that is needed to compile it successfully for nv_small?
