### ISSUE TITLE
An error while runing prebuilt nvdla_compiler

### ISSUE THREAD

**Issue by ericrxw** [nvdla/sw#15]
I'm trying to generate the loadable file of lenet with prebuilt nvdla_compiler in sw/, but I have the following error.

symbol lookup error: /ubc/ece/home/ml/grads/xiaowei/My_work/ML_accelerators/nvdla/sw/prebuilt/linux/libnvdla_compiler.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv

Because we do not have the source code of compiler, can you guys tell me what's the reason and how to solve it?
Thank you very much.

**Comment by arcbbb** [comment]
I use an old version (v2.6.1) of protobuf to solve it.
You can try this [https://github.com/google/protobuf/releases/tag/v2.6.1](url)

**Comment by ericrxw** [comment]
Yes, I solved the problem with the same solution. But I think we have to
use the GCC which version is lower than 5.0
Thank you very much.

**Comment by prasshantg** [comment]
@ericrxw please try using latest nvdla_compiler, we have linked protobuf statically so you should not observe this issue now

**Comment by prasshantg** [comment]
Closing this issue as protobuf is not statically linked. Please reopen if issue is observed
