### ISSUE TITLE
'KmdRunScript' object has no attribute 'serverlinebuffer' in regression test.

### ISSUE THREAD

**Issue by arvindhbti** [nvdla/sw#160]
Hi @prasshantg find below my error.

Platform is : linux

when i am running:
python kmdrun.py --ssh --odir /home/sandisk/Desktop/nvdla/sw/regression/scripts/out/CDP_L0_0_66cb25 --guid 66cb25 -o output.log -t CDP_L0_0 --project dla --target sim --os linux --debug 0 --testhome /home/sandisk/Desktop/nvdla/sw/regression/flatbufs --goldhome /home/sandisk/Desktop/nvdla/sw/regression/golden --noclean --show

i am getting this error:

################################################################################
                                Test   CDP_L0_0                                 
################################################################################
Wed Sep 11 10:37:21 2019 on sandisk-usb-sys
Command: kmdrun.py --ssh --odir /home/sandisk/Desktop/nvdla/sw/regression/scripts/out/CDP_L0_0_66cb25 --guid 66cb25 -o output.log -t CDP_L0_0 --project dla --target sim --os linux --debug 0 --testhome /home/sandisk/Desktop/nvdla/sw/regression/flatbufs --goldhome /home/sandisk/Desktop/nvdla/sw/regression/golden --noclean --show
ssh cmd: ssh root@127.0.0.1 -p 6667 export LD_LIBRARY_PATH=/mnt && /mnt/nvdla_runtime -s
Waiting for server ready...
Failed to launch test server
Let's try again
ssh cmd: ssh root@127.0.0.1 -p 6667 "ps | grep '/mnt/nvdla_runtime -s' | awk '{print $1}' | xargs kill"
ssh cmd: ssh root@127.0.0.1 -p 6667 export LD_LIBRARY_PATH=/mnt && /mnt/nvdla_runtime -s
Waiting for server ready...
Failed to launch test server
Let's try again
ssh cmd: ssh root@127.0.0.1 -p 6667 "ps | grep '/mnt/nvdla_runtime -s' | awk '{print $1}' | xargs kill"
ssh cmd: ssh root@127.0.0.1 -p 6667 export LD_LIBRARY_PATH=/mnt && /mnt/nvdla_runtime -s
Waiting for server ready...
Failed to launch test server
Let's try again
ssh cmd: ssh root@127.0.0.1 -p 6667 "ps | grep '/mnt/nvdla_runtime -s' | awk '{print $1}' | xargs kill"
Launching test: python /home/sandisk/Desktop/nvdla/sw/regression/scripts/dla_client.py -i /home/sandisk/Desktop/nvdla/sw/regression/flatbufs/kmd/CDP/CDP_L0_0_fbuf -o /home/sandisk/Desktop/nvdla/sw/regression/scripts/out/CDP_L0_0_66cb25
Traceback (most recent call last):
  File "kmdrun.py", line 51, in <module>
    main()
  File "kmdrun.py", line 42, in main
    runScript.runTest()
  File "/home/sandisk/Desktop/nvdla/sw/regression/scripts/KmdRunScript.py", line 171, in runTest
    while self.serverlinebuffer:
AttributeError: 'KmdRunScript' object has no attribute 'serverlinebuffer'

and yeah i am running ./nvdla_runtime -s in virtual platform in different terminal.

Question:
1) Please can you share with me testing steps.
2) If i want to test my ResNet50 then how to give those flatbuffs and golden input and all. Please suggest some steps.
3) How to run run_regression.py for ResNet50.

@prasshantg please help me in solving these wuestion and above error.Thanks.

**Comment by arvindhbti** [comment]
Hi @prasshantg can you please help me.
when i am running server and then regression test then i am getting this error at server side.


# ./nvdla_runtime -s
using 0.0.0.0, listening at port:6666
binding successful.
Ready for Client Connection...
Waiting for command from Client...
Received command: {GET_WELCOME}
Sending welcome message: {Hello World!}
Sending size 12 bytes.
Waiting for command from Client...
Received command: {READ_FLATBUF}
Waiting for command from Client...
Received command: {RUN_FLATBUF}
Executing the Test...
creating new runtime context...
Emulator starting
Unknown image type: submitting tasks...
Work Found!
Work Done
[   92.966901] Enter:dla_read_network_config
[   92.973023] Exit:dla_read_network_config status=0
[   92.973688] Enter: dla_initiate_processors
[   92.974909] Enter: dla_submit_operation
[   92.975313] Prepare Convolution operation index 0 ROI 0 dep_count 1
[   92.979115] Enter: dla_prepare_operation
[   92.982543] processor:Convolution group:0, rdma_group:0 available
[   92.983423] Enter: dla_read_config
[   92.991415] Exit: dla_read_config
[   92.994544] Exit: dla_prepare_operation status=0
[   92.995221] Enter: dla_program_operation
[   92.995637] Program Convolution operation index 0 ROI 0 Group[0]
[   93.007468] no desc get due to index==-1
[   93.008502] no desc get due to index==-1
[   93.008908] no desc get due to index==-1
[   93.009298] no desc get due to index==-1
[   93.009687] no desc get due to index==-1
[   93.010109] Enter: dla_op_programmed
[   93.010847] Update dependency operation index 3 ROI 0 DEP_COUNT=3
[   93.011388] Update dependency operation index 1 ROI 0 DEP_COUNT=1
[   93.017927] enable SDP in dla_update_dependency as depdency are resolved
[   93.018654] Enter: dla_enable_operation
[   93.019118] exit dla_enable_operation without actual enable due to processor hasn't been programmed
[   93.022736] Exit: dla_enable_operation status=0
[   93.023439] Exit: dla_op_programmed
[   93.026215] Exit: dla_program_operation status=0
[   93.026864] Exit: dla_submit_operation
[   93.027666] Enter: dla_dequeue_operation
[   93.031030] Dequeue op from Convolution processor, index=3 ROI=0
[   93.033994] Enter: dla_submit_operation
[   93.034504] Prepare Convolution operation index 3 ROI 0 dep_count 2
[   93.035032] Enter: dla_prepare_operation
[   93.035593] processor:Convolution group:1, rdma_group:0 available
[   93.039398] Enter: dla_read_config
[   93.042415] Exit: dla_read_config
[   93.042827] Exit: dla_prepare_operation status=0
[   93.043236] Enter: dla_program_operation
[   93.043604] Program Convolution operation index 3 ROI 0 Group[1]
[   93.050169] no desc get due to index==-1
[   93.050820] no desc get due to index==-1
[   93.051207] no desc get due to index==-1
[   93.051565] no desc get due to index==-1
[   93.056671] no desc get due to index==-1
[   93.057134] Enter: dla_op_programmed
[   93.057488] Update dependency operation index 6 ROI 0 DEP_COUNT=3
[   93.057978] Update dependency operation index 4 ROI 0 DEP_COUNT=2
[   93.058458] Exit: dla_op_programmed
[   93.058786] Exit: dla_program_operation status=0
[   93.059186] Exit: dla_submit_operation
[   93.059638] Exit: dla_dequeue_operation
[   93.065621] Enter: dla_submit_operation
[   93.066075] Prepare SDP operation index 1 ROI 0 dep_count 0
[   93.066527] Enter: dla_prepare_operation
[   93.067099] processor:SDP group:0, rdma_group:0 available
[   93.067562] Enter: dla_read_config
[   93.072537] Exit: dla_read_config
[   93.073176] Exit: dla_prepare_operation status=0
[   93.073655] Enter: dla_program_operation
[   93.074025] Program SDP operation index 1 ROI 0 Group[0]
[   93.081945] no desc get due to index==-1
[   93.082442] no desc get due to index==-1
[   93.082878] no desc get due to index==-1
[   93.083239] no desc get due to index==-1
[   93.083644] Enter: dla_op_programmed
[   93.087331] Update dependency operation index 4 ROI 0 DEP_COUNT=1
[   93.090247] enable SDP in dla_update_dependency as depdency are resolved
[   93.090845] Enter: dla_enable_operation
[   93.091274] exit dla_enable_operation without actual enable due to processor hasn't been programmed
[   93.094737] Exit: dla_enable_operation status=0
[   93.095247] Exit: dla_op_programmed
[   93.095590] Exit: dla_program_operation status=0
[   93.099014] Enter: dla_enable_operation
[   93.099644] Enable SDP operation index 1 ROI 0
[   93.103159] Enter: dla_op_enabled
[   93.103636] Update dependency operation index 0 ROI 0 DEP_COUNT=1
[   93.106540] enable Convolution in dla_update_dependency as depdency are resolved
[   93.107209] Enter: dla_enable_operation
[   93.107571] Enable Convolution operation index 0 ROI 0
[   93.115236] Enter: dla_op_enabled
[   93.116218] Exit: dla_op_enabled
[   93.116607] Exit: dla_enable_operation status=0
[   93.117049] Exit: dla_op_enabled
[   93.117384] Exit: dla_enable_operation status=0
[   93.117795] Exit: dla_submit_operation
[   93.118148] Enter: dla_dequeue_operation
[   93.118514] Dequeue op from SDP processor, index=4 ROI=0
[   93.118961] Enter: dla_submit_operation
[   93.119325] Prepare SDP operation index 4 ROI 0 dep_count 0
[   93.125921] Enter: dla_prepare_operation

Info: NV_NVDLA_cdma.cpp: 1265:NV_NVDLA_cdma::DirectConvDataResponseSequencerCommon, invalid configuration cdma_entries_, set value is 0x6, it shall be 0x7FF.
[   93.610923] processor:SDP group:1, rdma_group:1 available
[   93.611508] Enter: dla_read_config
[   93.614812] Exit: dla_read_config
[   93.615254] Exit: dla_prepare_operation status=0
[   93.615656] Enter: dla_program_operation
[   93.619059] Program SDP operation index 4 ROI 0 Group[1]
[   93.644484] no desc get due to index==-1
[   93.645142] no desc get due to index==-1
[   93.645586] no desc get due to index==-1
[   93.645943] no desc get due to index==-1
[   93.646305] Enter: dla_op_programmed
[   93.646663] Update dependency operation index 7 ROI 0 DEP_COUNT=2
[   93.647160] Exit: dla_op_programmed
[   93.647498] Exit: dla_program_operation status=0
[   93.653906] Enter: dla_enable_operation
[   93.654550] Enable SDP operation index 4 ROI 0
[   93.657485] Enter: dla_op_enabled
[   93.661271] Update dependency operation index 3 ROI 0 DEP_COUNT=2
[   93.661763] Exit: dla_op_enabled
[   93.662079] Exit: dla_enable_operation status=0
[   93.662467] Exit: dla_submit_operation
[   93.662817] Exit: dla_dequeue_operation
[   93.663177] Enter: dla_submit_operation
[   93.663540] Prepare PDP operation index 2 ROI 0 dep_count 1
[   93.669440] Enter: dla_prepare_operation
[   93.671464] processor:PDP group:0, rdma_group:0 available
[   93.674694] Enter: dla_read_config
[   93.675453] Exit: dla_read_config
[   93.678468] Exit: dla_prepare_operation status=0
[   93.678999] Enter: dla_program_operation
[   93.679377] Program PDP operation index 2 ROI 0 Group[0]
[   93.682701] group id 0 rdma id 0
[   93.688852] Invalid dst_data.mem_type: 9216
[   93.689484] Exit: dla_program_operation status=-3
[   93.689907] Exit: dla_submit_operation
[   93.690310] Failed to submit PDP op from index 2
[   93.690753] Exit: dla_initiate_processors status=-3
[   93.691301] Task execution failed
NvDlaSubmit: Error IOCTL failed (No such process)
(DLA_RUNTIME) Error 0x0003000f: (propagating from Runtime.cpp, function submitInternal(), line 666)
(DLA_TEST) Error 0x00000004: runtime->submit() failed (in RuntimeTest.cpp, function runTest(), line 387)
(DLA_TEST) Error 0x00000004: (propagating from RuntimeTest.cpp, function run(), line 440)


Thanks.

**Comment by arvindhbti** [comment]
Hi @prasshantg  can you please help me in solving above these issues.Thanks.

**Comment by xiao777dong** [comment]
I've met the same problem. Have you solved the problem yet?

**Comment by arvindhbti** [comment]
Hey @xiao777dong

Declare serverlinebuffer globally.Actually it is declared locally in function.
Mine working fine after declaring global.
Thanks.
