### ISSUE TITLE
Compilation of GoogleNet fails

### ISSUE THREAD

**Issue by ned-varnica** [nvdla/sw#17]
This was posted by someone in Issue#4 that was closed, but this particular issue was not resolved.  Re-opening here and hoping someone can point me in the right direction how to compile GoogleNet.  Thanks!  

For GoogleNet, compilation output is as follows:  
....
creating new wisdom context...
opening wisdom context...
parsing caffe network...
Marking output [0] for layer prob
attaching parsed network to the wisdom...
compiling profile "default"...
libnvdla<3> compile network
libnvdla<3> compile201
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
libnvdla<3> concat-node's output surface format NVDLA_FEATURE_DATA_FP16
(DLA) Error 0x0000000b: Consumer of type CONVOLUTION already exists for node pdp-0 : conv-0 that is not connected via compute dependency to what we see now (in engine-ast/EngineNode.cpp, function resolveDataDependencies(), line 662)
(DLA) Error 0x0000000b: conv-1, FIXME!!! (in engine-ast/EngineNode.cpp, function resolveDataDependencies(), line 663)
(DLA) Error 0x0000000b: (propagating from engine-ast/EngineGraph.cpp, function resolveDataDependencies(), line 794)
(DLA) Error 0x0000000b: (propagating from Compiler.cpp, function resolveDataDependencies(), line 1110)
(DLA) Error 0x00000008: failed compilation phase: resolveDataDependencies (propagating from Compiler.cpp, function compile(), line 3
(DLA) Error 0x00000004: compiler->compile("default") failed (in CompileTest.cpp, function compileProfile(), line 48)
(DLA) Error 0x00000004: (propagating from ParseTest.cpp, function parseAndCompile(), line 174)
(DLA) Error 0x00000004: (propagating from main.cpp, function launchTest(), line 79)
....

**Comment by prasshantg** [comment]
@ned-varnica currently NVDLA compiler does not support googlenet graph, adding it to future release

**Comment by ned-varnica** [comment]
Thanks for the update.  Much appreciated.
