### ISSUE TITLE
how to exit qemu to docker shell?

### ISSUE THREAD

**Issue by andyzheng-snps** [nvdla/sw#183]
I use docker to run vp env.  However I input exit command at the qemu simulator, it only exits to nvdla login state.  I want to exit to docker shell.
# exit
Welcome to Buildroot
nvdla login: 

who can give me help?

thanks

**Comment by prasshantg** [comment]
It is "Ctrl+A X"

1. Press Ctrl
2. Press and release A
3. Release Ctrl
4. Press X

**Comment by andyzheng-snps** [comment]
it is amazing!

thanks for your help.
