### ISSUE TITLE
Does the current released nvdla_compiler support TensorFlow?

### ISSUE THREAD

**Issue by chagyun0213** [nvdla/sw#2]
Hi
Could you confirm whether this released compiler could parse Tensorflow *.uff or *.pbtxt file?
If not, when it would be supported?
Thanks,

./nvdla_compiler -h
Usage: ./nvdla_compiler [-options] --prototxt <prototxt_file> --caffemodel <caffemodel_file> -o <outputpath>

**Comment by prasshantg** [comment]
No, currently released compiler does not support TensorFlow. We are going to support it but there is no defined timeline for it yet. We will update here once we have timeline for it.

**Comment by chagyun0213** [comment]
OK. That's fine.
I am not clear about its coverage. 
I do understand that this compiler supports only nvdla1 release(nv_full configuration).
Is it correct? If so, when do you plan to release other supporting nv_small configuration, roughly?  
If this version supports nv_small, how do I setup for that?

**Comment by prasshantg** [comment]
Yes, current compiler supports only nv_full. Roughly we plan to support small config with FP16 by Jan end but there are high chances that this will change.

**Comment by chagyun0213** [comment]
Thanks a lot!

**Comment by Adithyak1998** [comment]
Is it supported now?
If yes, please let me know the syntax for nvdla_compiler
