### ISSUE TITLE
Can c model provide the DRAM traffic information

### ISSUE THREAD

**Issue by HKLee2040** [nvdla/sw#22]
According to the following issue
https://github.com/nvdla/hw/issues/96

Can NVDLA c model provide the DRAM traffic information to evaluate the bandwidth behavior?

**Comment by HKLee2040** [comment]
If NV will release customizable compiler, I think such information could help us to do parameters optimization.

**Comment by jwise** [comment]
I don't think it natively has support for that, but you may be able to instrument NV_NVDLA_mcif.cpp to get the information you're looking for there.

**Comment by prasshantg** [comment]
Alternatively you can enable memory transaction log using environment variable 'SC_LOG'

export SC_LOG="outfile:sc.log;verbosity_level:sc_debug;:warning;nvdla.dbb_adaptor:enable;nvdla.sram_adaptor:enable"

**Comment by prasshantg** [comment]
Closing issue, please re-open any more questions on this topic
