### ISSUE TITLE
Error of "nvdla_compiler" converting FP16 NVCaffe model into loadable file

### ISSUE THREAD

**Issue by jeongc** [nvdla/sw#23]
Hi,

I tried to convert caffemodels into NVDLA loadables using BVLC Caffe (FP32) and NVCaffe-0.16.6(FP16).
I did follow the following link to create FP16 caffe model - fp16_mnist
http://docs.nvidia.com/deeplearning/sdk/mixed-precision-training/index.html
with these parameters:

// net prototxt
default_forward_math: FLOAT16
default_backward_math: FLOAT16
// solver prototxt
solver_data_type: FLOAT16

Here is my output.

**Converting BVLC FP32 Caffe model**

jeongc@jeongc-dl:/dla/vp/nets/bvlc_mnist$ ls
default.nvdla lenet_deploy.prototxt lenet_iter_10000.caffemodel output.protobuf wisdom.dir
jeongc@jeongc-dl:/dla/vp/nets/bvlc_mnist$ rm -rf default.nvdla wisdom.dir output.protobuf
jeongc@jeongc-dl:/dla/vp/nets/bvlc_mnist$ ls
lenet_deploy.prototxt lenet_iter_10000.caffemodel
jeongc@jeongc-dl:/dla/vp/nets/bvlc_mnist$ mkdir nvdla
jeongc@jeongc-dl:/dla/vp/nets/bvlc_mnist$ nvdla_compiler --prototxt lenet_deploy.prototxt --caffemodel lenet_iter_10000.caffemodel -o nvdla
creating new wisdom context...
opening wisdom context...
parsing caffe network...
Marking output [0] for layer loss
attaching parsed network to the wisdom...
compiling profile "default"...
libnvdla<3> compile network
libnvdla<3> compile203
profile compiled "default"...
closing wisdom context...
jeongc@jeongc-dl:/dla/vp/nets/bvlc_mnist$ ls
default.nvdla lenet_deploy.prototxt lenet_iter_10000.caffemodel nvdla nvdlawisdom.dir output.protobuf

**Converting FP16 NVCaffe-0.16.6 model**

jeongc@jeongc-dl:/dla/vp/nets/bvlc_mnist$ cd ../fp16_mnist/
jeongc@jeongc-dl:/dla/vp/nets/fp16_mnist$ ls
lenet_deploy_fp16.prototxt lenet_fp16_iter_10000.caffemodel
jeongc@jeongc-dl:/dla/vp/nets/fp16_mnist$ mkdir nvdla
jeongc@jeongc-dl:/dla/vp/nets/fp16_mnist$ nvdla_compiler --prototxt lenet_deploy_fp16.prototxt --caffemodel lenet_fp16_iter_10000.caffemodel -o nvdla
creating new wisdom context...
opening wisdom context...
parsing caffe network...
conv1: ERROR - 32-bit weights not found for 32-bit model
conv1: ERROR - 32-bit weights not found for 32-bit model
libnvdla<1> Parameter check failed in addConvolution, condition: kernelWeights.values != 0
libnvdla<1> error: parsing layer type Convolution index 2
(DLA) Error 0x00000004: Unable to parse caffemodel: "lenet_deploy_fp16.prototxt" (in ParseTest.cpp, function parseCaffeNetwork(), line 91)
(DLA) Error 0x00000004: (propagating from ParseTest.cpp, function parseAndCompile(), line 169)
(DLA) Error 0x00000004: (propagating from main.cpp, function launchTest(), line 79)
jeongc@jeongc-dl:~/dla/vp/nets/fp16_mnist$

Could you explain how to resolve this error?

Regards,
CJ

**Comment by prasshantg** [comment]
@jeongc NVDLA compiler does not support FP16 model as input. It takes FP32 model as input and converts that to FP16 as per DLA requirement.

**Comment by jeongc** [comment]
Hi 

Thanks for your reply. 
If nvdla_compiler converts FP32 into FP16, how about data loss during conversion? 
Or do you mean I have to train in FP16 and have to save as FP32 using "store_blobs_in_old_format"?
Please explain in detail. 
Thanks in advance.

CJ

**Comment by prasshantg** [comment]
Hi @jeongc 

There would be some precision loss if your model is trained in FP32. It depends on the dynamic range of data in model.

Training in FP16 and saving that in FP32 would have minimum precision loss as the dynamic range would be within FP16 limit.
