### ISSUE TITLE
UMD compilation on target fails

### ISSUE THREAD

**Issue by lakamath** [nvdla/sw#237]
Hi,

i am trying to compile UMD on Agilex SOC (ARM). with yocto.
i am using command make TOOLCHAIN_PREFIX=/usr/bin/ compiler ROOT="${TOP}"
but i am getting build error as shown below

linking /home/root/nvdla_umd_build/umd/out/apps/compiler/nvdla_compiler/nvdla_compiler.mod.o
ld -r /home/root/nvdla_umd_build/umd/out/apps/compiler/nvdla_compiler/main.o /home/root/nvdla_umd_build/umd/out/apps/compiler/nvdla_compiler/CompileTest.o /home/root/nvdla_umd_build/umd/out/apps/compiler/nvdla_compiler/GenerateTest.o /home/root/nvdla_umd_build/umd/out/apps/compiler/nvdla_compiler/ParseTest.o -o /home/root/nvdla_umd_build/umd/out/apps/compiler/nvdla_compiler/nvdla_compiler.mod.o
make[1]: *** No rule to make target '/home/root/nvdla_umd_build/umd/out/core/src/compiler/libnvdla_compiler/libnvdla_compiler.so', needed by '/home/root/nvdla_umd_build/umd/out/apps/compiler/nvdla_compiler/nvdla_compiler'.  Stop.
make[1]: Leaving directory '/home/root/nvdla_umd_build/umd/apps/compiler'
make: *** [Makefile:35: compiler] Error 2
root@agilexfm61:~/nvdla_umd_build/umd#

in Makefile i see the target rule for compiler  but where is the rule to build $(SHARED_LIBS)

# the logic to compile and link stuff is in here
$(TEST_BIN): $(ALLMODULE_OBJS) $(SHARED_LIBS)
	@echo building $(MODULE)  $@
	g++ $(ALLMODULE_OBJS) -L$(ROOT)/out/core/src/compiler/libnvdla_compiler libprotobuf.a -lnvdla_compiler -pthread -o $@ libprotobuf.a -Wl,-rpath=.

**Comment by long771** [comment]
这是来自QQ邮箱的自动回复邮件。 您好，我是龙欣荣，很高兴收到您的邮件，我将尽快处理。

**Comment by lakamath** [comment]
issue in header
