### ISSUE TITLE
What can we extract in general from the runtime_nvdla test ?

### ISSUE THREAD

**Issue by Y159753** [nvdla/sw#28]
Hello, 
I try to launch runtime_nvdla in a docker container with an axelnet from berkeley's github caffe examples, and a wonderful dalmatian dog pgm image for testing.  I have three questions about this runtime_nvdla test 

What can I extract from this first simulation ?  

Do I have to re-insert code lines in RuntimeTest.cpp and recompile it to obtain more information than a "test passed" ? 
   
If so, what information about the performance of the NVDLA can I retrieve in general ? What are the commands to use ? (My goal is to integrate the NVDLA in a FPGA)

**Comment by prasshantg** [comment]
Test application has an option --output to dump output of final layer. It will dump output to a file.

Please use "nvdla_runtime --help" to check the options available.

**Comment by Y159753** [comment]
Thank you once again. After checking the "output" option was not displayed in the help.  

# ./nvdla_runtime --help
Usage: ./nvdla_runtime [-options] --loadable <loadable_file>
where options include:
    -h               print this help message
    -s               launch test in server mode
    --loadable <loadable_file>
    --image <image_file>
    --imgshift <shift_value>
    --imgscale <scale_value>
    --imgpower <power_value>
    --softmax

**Comment by JunningWu** [comment]
@Y159753 Please update your code

**Comment by Y159753** [comment]
ok the code is changing pretty fast. I do that.

**Comment by Y159753** [comment]
I am afraid to say something irrelevant but, the option is not available even after pulling again the "sw" repository (with simple "git pull" inside my local sw repo). 
I also pulled again the docker image ("sudo docker image pull nvdla/vp") and relaunched the virtual platform in a new container. Everything is supposed to be up to date. 
Anyway I started to use your software after your last commit.

I tried to run the --output option anyway, and it does not work.  
   
./nvdla_runtime  --loadable default.nvdla  --image dog_227x227.jpg --output ./
      
Usage: ./nvdla_runtime [-options] --loadable <loadable_file>
where options include:
    -h               print this help message
    -s               launch test in server mode
    --loadable <loadable_file>
    --image <image_file>
    --imgshift <shift_value>
    --imgscale <scale_value>
    --imgpower <power_value>
    --softmax

**Comment by JunningWu** [comment]
replace the nvdla_runtime obj file in VP.

**Comment by Y159753** [comment]
thanks it works, the option is --rawdump

Usage: ./nvdla_runtime2 [-options] --loadable <loadable_file>
where options include:
    -h               print this help message
    -s               launch test in server mode
    --image <file>   input jpg/pgm file
    --rawdump        dump raw dimg data
