### ISSUE TITLE
how to install SW in QEMU

### ISSUE THREAD

**Issue by ShoneAlbert** [nvdla/sw#3]
According to the doc, I have installed Qbox in my machine. And I can run "hello world". But how to install SW in it. 
And if I have a caffe model , the ptotxt file and how to continue the  inference process.

**Comment by wujunning2011** [comment]
good question, waiting for it!

**Comment by jwise** [comment]
I think this is a duplicate of nvdla/vp#1; I'll close it as such.  (In the future, you only need to open one ticket per issue.)  Thanks for your interest in NVDLA!
