### ISSUE TITLE
nvdla_runtime: cannot execute binary file

### ISSUE THREAD

**Issue by pochen125** [nvdla/sw#34]
Hi~~~

I got this error following
1. ./nvdla_runtime --loadable default.nvdla --image seven.pgm
bash: ./nvdla_runtime: cannot execute binary file: Exec format error
when I change this the same
root@pochen125-VirtualBox:~/sw/prebuilt/linux# ./nvdla_runtime
bash: ./nvdla_runtime: cannot execute binary file: Exec format error

It cannot run anything

**Comment by jwise** [comment]
nvdla_runtime is an ARM binary that runs on the ARM virtual platform environment on DLA, not on a host machine.
