### ISSUE TITLE
./nvdla_runtime: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by pochen125** [nvdla/sw#35]
hi~~

I got this problem

root@pochen125-VirtualBox:~/sw/prebuilt/linux# ./nvdla_runtime --loadable default.nvdla --image seven.pgm
i change this the same error.

root@pochen125-VirtualBox:~/sw/prebuilt/linux# ./nvdla_runtime
bash: ./nvdla_runtime: cannot execute binary file: Exec format error

**Comment by jwise** [comment]
This is the same as #34, right?
