### ISSUE TITLE
How to process video (not single image) without reloading loadable file?

### ISSUE THREAD

**Issue by chagyun0213** [nvdla/sw#38]
Hi

Based on my understanding, the current nvdla_runtime does inference on one input image as
1. createRuntime()
2. readLoadable()
3. loadLoadable()
4. runTest() 
5. end

But I saw it takes lots of time, especially, during the above step 1.
Basically, I want to do multiple inferences to process video by loading a loadable one time. 
I tried looping the above step 4, and I saw the first inference is good, but it hangs when it does the second loop. I am speculating some states are not initialized properly.
My question is do I  repeat "both step 3 and step 4" for every inference?  Or please provide some hints.

Thanks,
CJ

**Comment by prasshantg** [comment]
Yes, currently you will have to repeat both step 3 and step 4 as there is some data that overwritten by low level driver and has to reloaded by executing loadLoadable step.

**Comment by chagyun0213** [comment]
Hi 
I did test with simple modification - just looping 2 times with same image like

-------------------------------------------------------------------------------------------------
NvDlaError run(const TestAppArgs* appArgs, TestInfo* i)
{
    NvDlaError e = NvDlaSuccess;

    NvDlaDebugPrintf("creating new runtime context...\n");
    i->runtime = nvdla::createRuntime();
    if (!i->runtime)
        ORIGINATE_ERROR_FAIL(NvDlaError_BadParameter, "createRuntime() failed");

    if ( !i->dlaServerRunning ) {
        NvDlaDebugPrintf("reading loadable...\n");
        PROPAGATE_ERROR_FAIL(readLoadable(appArgs, i));
    }

    for(int k = 0; k<2;k++) {
    NvDlaDebugPrintf("loading loadable...\n");
    PROPAGATE_ERROR_FAIL(loadLoadable(appArgs, i));

    NvDlaDebugPrintf("launching test...\n");
    PROPAGATE_ERROR_FAIL(runTest(appArgs, i));
    }

fail:
    return e;
}
-----------------------------------------------------------------------------------------------------------------------------

But I go "Segmentation fault"

// I deleted lots of lines....

[ 1272.752056] Exit:dla_handle_events, ret:0
[ 1272.752181] Enter:dla_handle_events, processor:RUBIK
[ 1272.752332] Exit:dla_handle_events, ret:0
[ 1272.755193] reset engine done                 **// Here 1st loop has done**

loading loadable...                                          **// Here 2nd runtest starts**
(DLA_RUNTIME) Error 0x00000004: Duplicate bind ids on separate memory objects in runtime. (in Runtime.cpp, function initBindableMemory(), line 772)
(DLA_RUNTIME) Error 0x00000004: (propagating from Runtime.cpp, function load(), line 286)
launching test...
input dims = (1, 1, 28, 28)
testing_pgm/0/10.pgm, -1
ppgminfo 1 28 28
pgm2dimg 1 28 28 1 32 896 896
submitting tasks...
libnvdla<1> fillTaskAddressList ali=0 -> mem_id=18 has a null memory handle.
[ 1274.218951] nvdla_runtime[1281]: unhandled level 2 translation fault (11) at 0x00000000, esr 0x92000006, in libnvdla_runtime.so[ffffbc615000+32000]
[ 1274.223694] CPU: 0 PID: 1281 Comm: nvdla_runtime Tainted: G           O    4.13.3 #1
[ 1274.223986] Hardware name: linux,dummy-virt (DT)
[ 1274.224258] task: ffff80003da83800 task.stack: ffff80003d004000
[ 1274.224691] PC is at 0xffffbc62c33c
[ 1274.224815] LR is at 0xffffbc632d6c
[ 1274.224953] pc : [<0000ffffbc62c33c>] lr : [<0000ffffbc632d6c>] pstate: 80000000
[ 1274.225221] sp : 0000ffffdf2d0950
[ 1274.225400] x29: 0000ffffdf2e8980 x28: 0000000008af86c0 
[ 1274.225643] x27: 0000000008b0e980 x26: 0000000008af7d48 
[ 1274.225843] x25: 0000000008af7d30 x24: 0000000008b0e980 
[ 1274.226024] x23: 0000000000000000 x22: 0000000000000000 
[ 1274.227221] x21: 0000000000000000 x20: 0000ffffdf2e8a50 
[ 1274.227411] x19: 0000000008af7c40 x18: 0000000000000000 
[ 1274.227615] x17: 0000ffffbc62c244 x16: 0000ffffbc6576f8 
[ 1274.227819] x15: 00000000000009aa x14: 2e656c646e616820 
[ 1274.228018] x13: 0000000000000000 x12: 6c756e2061207361 
[ 1274.228233] x11: 0000000000000032 x10: 0000000000000000 
[ 1274.228432] x9 : 0000000000018010 x8 : 0000000000000018 
[ 1274.228603] x7 : 0000000008af86c0 x6 : 0000ffffdf2d0980 
[ 1274.228788] x5 : 0000ffffdf2e8a68 x4 : 0000ffffdf2e8970 
[ 1274.228965] x3 : 0000ffffdf2e8be8 x2 : 0000ffffdf2e8a68 
[ 1274.229149] x1 : 0000ffffdf2d0950 x0 : 0000ffffdf2d0970 
Segmentation fault
# 

I believe loading a loadable per image(frame) is not optimal. I hope it should be improved. 

Regards,
CJ

**Comment by prasshantg** [comment]
@chagyun0213 we have fixed this issue, can you please try repeating just step 4 with latest code?

**Comment by chagyun0213** [comment]
@prasshangtg
Thanks for your immediate help. Your fix works very well. Closing the issue.
Best Regards,
CJ

**Comment by prasshantg** [comment]
@chagyun0213 thanks for finding it out, will get back next week.

**Comment by kkudryavtsev** [comment]
We have the same problem with the speed. Does your "sever mode" supports multiple image processing without reloading loadable?

**Comment by chagyun0213** [comment]
Hi
I did debug and figured out the followings need improvement to process video continuously.
1. std::queue is not thread-safe, needs mutex protection.
2. have to clean up mixing usage of malloc with new/new[]. 
3. memory leaks. Allocated temporary memories should be freed.

**Comment by prasshantg** [comment]
@chagyun0213 thank you figuring out improvements required. We have provided fixes for 2 and 3. Please check with latest code. Looking into 1.

**Comment by prasshantg** [comment]
@chagyun0213 please let us know if you are still facing issues

**Comment by chagyun0213** [comment]
Hi 
Closing this issue since I can process incoming video without reloading loadable. 
Thanks for your support.

Regards,
