### ISSUE TITLE
Can I feed output.dimg as input to continue inference for NVDLA? 

### ISSUE THREAD

**Issue by MINZHIJI** [nvdla/sw#40]
I use `LeNet` as example.
Below model is `LeNet`. 
```
name: "LeNet"
layer {
  name: "data"
  type: "Input"
  top: "data"
  input_param { shape: { dim: 1 dim: 1 dim: 28 dim: 28 } }
}
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 20
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "conv1"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
.
.
. 
```
And I want to split inference by single layer or fewer layers. 
Such that I want to inference first convolution(`conv1`) and use rawdump to get `output.dimg` .
Then, I want to use `output.dimg`  to continue the rest of network (ex: pooling, relu, ... etc). 
**So I want to know `nvdla_runtime` can feed `output.dimg` and can feed more batch?**

**Comment by prasshantg** [comment]
Test application does not support it but you can try to implement it. Source code for test application and utility functions for .dimg files are at https://github.com/nvdla/sw/tree/master/umd/tests/runtime
