### ISSUE TITLE
Neural Net integrations open questions

### ISSUE THREAD

**Issue by Y159753** [nvdla/sw#42]
You don't discuss so much about that in the documentation, I understand it is not a closed topic but I would like to have some hints about this : 

How to optimize the hardware for a given neural net ? What kind of approach would you advise ?

Does any neural net will fit on any configuration of the NVDLA but at the cost of big timing delay or power consumption ?

**Comment by Y159753** [comment]
I thought the software team was also involved in those reflections. I reposted it in the correct section https://github.com/nvdla/hw/issues/133

**Comment by jwise** [comment]
Thanks, I've answered in that bug.
