### ISSUE TITLE
Can I run image classfication with cifar10_quick?

### ISSUE THREAD

**Issue by MINZHIJI** [nvdla/sw#44]
**Environment:**
* OS: Ubuntu 14.04
* NVDLA Version: NV_FULL
* Model: cifar10_quick ([Link](https://github.com/BVLC/caffe/tree/master/examples/cifar10))
* Data-set: cifar10

**Question:**
I run cifar10_quick which is compiled by nvdla_compiler and I use nvdla_runtime to run cifar10_quick.
But the runtime is no response for a long time!  **[Solved]**
**New problem is the output results are similar!**
I try three cases!
**Results**
```
[test/0_cat.jpg]
result:
0.0689087 0.0415649 0.134766 0.111938 0.219238 0.0861206 0.10498 0.0811768 0.100342 0.0509338 

[train/27_dog.jpg]
result:
0.0667114 0.0420837 0.136597 0.111877 0.220703 0.086792 0.106567 0.079895 0.0982056 0.0506287 

[nope]    //   no input image
result:
0.0683594 0.0415344 0.140625 0.111206 0.224121 0.0821533 0.105042 0.0791626 0.097229 0.0505676 
```

**Comment by JunningWu** [comment]
2 HWLs done, totally 16 layers

**Comment by JunningWu** [comment]
@MINZHIJI have you tried some other resolution image, 3x227x227?
can you share your caffemodel?

**Comment by MINZHIJI** [comment]
**CIFAR10 Environment ([Link](https://drive.google.com/open?id=12A8qeOVghKnxo2trQqTSoD72h1zfXNMc))**
@JunningWu  I upload to google drive. There are input image, deploy.prototxt, caffemodel, and compiled loadable file.

**Comment by MINZHIJI** [comment]
@JunningWu  Thanks. 
I use new runtime to run cifar10 sucessfully.
But output results are very **strange**.
Result values are very closing!?
I try three cases!
**Results**
```
[test/0_cat.jpg]
result:
0.0689087 0.0415649 0.134766 0.111938 0.219238 0.0861206 0.10498 0.0811768 0.100342 0.0509338 
[train/27_dog.jpg]
result:
0.0667114 0.0420837 0.136597 0.111877 0.220703 0.086792 0.106567 0.079895 0.0982056 0.0506287 
[nope] // no input image
0.0683594 0.0415344 0.140625 0.111206 0.224121 0.0821533 0.105042 0.0791626 0.097229 0.0505676 
```

**Comment by JunningWu** [comment]
@MINZHIJI yeah，the simulation results are the same for 0_cat.jpg.

**Comment by prasshantg** [comment]
@MINZHIJI is this issue resolved with latest changes?

**Comment by MINZHIJI** [comment]
@prasshantg yes, thanks.
