### ISSUE TITLE
KMD rebuild

### ISSUE THREAD

**Issue by giusecesa4** [nvdla/sw#46]
I am trying to rebuild opennvdla_small.ko from kmd source files for a different kernel, but I receive an error like this:

>  kmd/port/linux/nvdla_gem.c: In function 'nvdla_gem_dma_addr':
>  kmd/port/linux/nvdla_gem.c:335:2: error: Implicit declaration of function 'drm_gem_object_put_unlocked'

has someone any idea about the problem?

**Comment by smsharif1991** [comment]
Hi @giusecesa4 , which kernel version you are using ??
For building opendla_small.ko you have to add  CFLAG_MODULE='-DDLA_SMALL_CONFIG' to the make command

**Comment by giusecesa4** [comment]
Ok, thank you, I'm able now to generate the open_small.ko file.
I see in the sw folder of the NVDLA that there is another file, called drm.ko. How can I generate this file?
I am now using the linux kernel 4.14.0, because I managed to generate all the image files with the Petalinux 2018.1 version

**Comment by prasshantg** [comment]
@giusecesa4 you should get drm.ko when you build modules for your linux kernel 4.14.0

**Comment by chagyun0213** [comment]
If your kernel is older than 4.13.0, you should use drm_gem_object_unreference_unlocked(obj) instead.

**Comment by prasshantg** [comment]
@giusecesa4 please follow #51 for KMD build issue, that should help you.

**Comment by monkeyking** [comment]
> If your kernel is older than 4.13.0, you should use drm_gem_object_unreference_unlocked(obj) instead.

LGTM :)
