### ISSUE TITLE
Separating loading of the NVDLA loadable and jpg image

### ISSUE THREAD

**Issue by ned-varnica** [nvdla/sw#52]
Hi, 
Is there a way to separate loading the NVDLA loadable and the jpg image.? We are trying to run an application with videos, but so far see only one way to do it: Load the loadable every time we load a frame (image).  This makes the system extremely slow,.  Can you please let us know a way to fix this (or if there is a fix coming for this)? 

thanks!

**Comment by prasshantg** [comment]
@ned-varnica we have fixed this issue in latest code. No need to load loadable for each image. Please verify it with latest and let us know if you still facing some issue.

**Comment by prasshantg** [comment]
@ned-varnica we are already tracking this feature/issue in #38
