### ISSUE TITLE
How to Debug Runtime Error

### ISSUE THREAD

**Issue by silvaurus** [nvdla/sw#61]
Hi! I used nvdla_runtime to run the cifar10_quick caffe model and it gave me an error, I'm wondering how I can debug an error like this. Thank you!

./nvdla_runtime --loadable basic.nvdla --image cat.jpg
creating new runtime context...
Emulator starting
surface format: 46
dlaimg height: 32 x 32 x 3: LS: 96 SS: 0 Size: 3072
submitting tasks...
[  269.118559] Enter:dla_read_network_config
[  269.122494] Exit:dla_read_network_config status=0
[  269.122707] Enter: dla_initiate_processors
[  269.126472] Enter: dla_submit_operation
[  269.126740] Prepare Convolution operation index 0 ROI 0 dep_count 1
[  269.128176] Enter: dla_prepare_operation
[  269.128737] processor:Convolution group:0, rdma_group:0 available
[  269.129044] Enter: dla_read_config
[  269.136948] Exit: dla_read_config
[  269.137113] Exit: dla_prepare_operation status=0
[  269.137331] Enter: dla_program_operation
[  269.137703] Program Convolution operation index 0 ROI 0 Group[0]
[  269.147063] no desc get due to index==-1
[  269.148182] no desc get due to index==-1
[  269.148365] no desc get due to index==-1
[  269.148535] no desc get due to index==-1
[  269.148728] no desc get due to index==-1
[  269.148920] Enter: dla_op_programmed
[  269.149190] Update dependency operation index 4 ROI 0 DEP_COUNT=3
[  269.149445] Update dependency operation index 1 ROI 0 DEP_COUNT=1
[  269.149701] enable SDP in dla_update_dependency as depdency are resolved
[  269.149976] Enter: dla_enable_operation
[  269.150165] exit dla_enable_operation without actual enable due to processor hasn't been programmed
[  269.150517] Exit: dla_enable_operation status=0
[  269.150751] Exit: dla_op_programmed
[  269.153628] Exit: dla_program_operation status=0
[  269.154047] Exit: dla_submit_operation
[  269.154277] Enter: dla_dequeue_operation
[  269.154465] Dequeue op from Convolution processor, index=4 ROI=0
[  269.154673] Enter: dla_submit_operation
[  269.154804] Prepare Convolution operation index 4 ROI 0 dep_count 2
[  269.154956] Enter: dla_prepare_operation
[  269.158239] processor:Convolution group:1, rdma_group:0 available
[  269.158556] Enter: dla_read_config
[  269.168414] Exit: dla_read_config
[  269.168609] Exit: dla_prepare_operation status=0
[  269.168798] Enter: dla_program_operation
[  269.168970] Program Convolution operation index 4 ROI 0 Group[1]
[  269.175347] no desc get due to index==-1
[  269.176528] no desc get due to index==-1
[  269.176681] no desc get due to index==-1
[  269.176848] no desc get due to index==-1
[  269.177015] no desc get due to index==-1
[  269.177187] Enter: dla_op_programmed
[  269.177354] Update dependency operation index 8 ROI 0 DEP_COUNT=3
[  269.177585] Update dependency operation index 5 ROI 0 DEP_COUNT=2
[  269.177826] Exit: dla_op_programmed
[  269.177974] Exit: dla_program_operation status=0
[  269.178158] Exit: dla_submit_operation
[  269.178371] Exit: dla_dequeue_operation
[  269.178584] Enter: dla_submit_operation
[  269.181239] Prepare SDP operation index 1 ROI 0 dep_count 0
[  269.181469] Enter: dla_prepare_operation
[  269.181933] processor:SDP group:0, rdma_group:0 available
[  269.182151] Enter: dla_read_config
[  269.197140] Exit: dla_read_config
[  269.197440] Exit: dla_prepare_operation status=0
[  269.197662] Enter: dla_program_operation
[  269.197842] Program SDP operation index 1 ROI 0 Group[0]
[  269.205616] no desc get due to index==-1
[  269.205946] no desc get due to index==-1
[  269.208286] no desc get due to index==-1
[  269.208476] no desc get due to index==-1
[  269.208636] Enter: dla_op_programmed
[  269.208797] Update dependency operation index 3 ROI 0 DEP_COUNT=2
[  269.209032] Exit: dla_op_programmed
[  269.209190] Exit: dla_program_operation status=0
[  269.209389] Enter: dla_enable_operation
[  269.209612] Enable SDP operation index 1 ROI 0
[  269.210191] Enter: dla_op_enabled
[  269.210368] Update dependency operation index 0 ROI 0 DEP_COUNT=1
[  269.210621] enable Convolution in dla_update_dependency as depdency are resolved
[  269.213058] Enter: dla_enable_operation
[  269.213252] Enable Convolution operation index 0 ROI 0
[  269.220125] Enter: dla_op_enabled
[  269.220378] Exit: dla_op_enabled
[  269.220533] Exit: dla_enable_operation status=0
[  269.220720] Exit: dla_op_enabled
[  269.220866] Exit: dla_enable_operation status=0
[  269.221220] Exit: dla_submit_operation
[  269.221425] Enter: dla_dequeue_operation
[  269.221552] Dequeue op from SDP processor, index=3 ROI=0
[  269.221712] Enter: dla_submit_operation
[  269.221875] Prepare SDP operation index 3 ROI 0 dep_count 1
[  269.222021] Enter: dla_prepare_operation
[  269.229488] processor:SDP group:1, rdma_group:1 available
[  269.229739] Enter: dla_read_config
[  269.273027] Exit: dla_read_config
[  269.273294] Exit: dla_prepare_operation status=0
[  269.273489] Enter: dla_program_operation
[  269.273664] Program SDP operation index 3 ROI 0 Group[1]
[  269.286416] no desc get due to index==-1
[  269.286694] no desc get due to index==-1
[  269.287912] no desc get due to index==-1
[  269.288093] no desc get due to index==-1
[  269.288245] no desc get due to index==-1
[  269.288379] Enter: dla_op_programmed
[  269.288540] Update dependency operation index 5 ROI 0 DEP_COUNT=1
[  269.288766] enable SDP in dla_update_dependency as depdency are resolved
[  269.289010] Enter: dla_enable_operation
[  269.289195] exit dla_enable_operation without actual enable due to processor hasn't been programmed
[  269.289512] Exit: dla_enable_operation status=0
[  269.289698] Exit: dla_op_programmed
[  269.289851] Exit: dla_program_operation status=0
[  269.290037] Exit: dla_submit_operation
[  269.290197] Exit: dla_dequeue_operation
[  269.290364] Enter: dla_submit_operation
[  269.290548] Prepare PDP operation index 2 ROI 0 dep_count 1
[  269.293452] Enter: dla_prepare_operation
[  269.294582] processor:PDP group:0, rdma_group:0 available
[  269.296521] Enter: dla_read_config

Error: (E115) sc_signal<T> cannot have more than one driver: 
 signal `nvdla.buffer_0' (sc_buffer)
 first driver `nvdla.nvdla_core.nvdla_core.glb.Update_nvdla_intr_cdma_wt_0'  (sc_method_process)
 second driver `nvdla.nvdla_core.nvdla_core.glb.Update_nvdla_intr_w' (sc_method_process)
In file: ../../../../src/sysc/communication/sc_signal.cpp:75
In process: nvdla.nvdla_core.nvdla_core.glb.Update_nvdla_intr_w @ 262500 ms

**Comment by chagyun0213** [comment]
You have to set before starting VP
$ export SC_SIGNAL_WRITE_CHECK=DISABLE

**Comment by cgl-nudt** [comment]
hi! I meet the same question, I want to know if you solve it and how to solve it. Thank you very much!

**Comment by silvaurus** [comment]
@cgl-nudt  Yes, like chagyun said,  I just forgot to `$export SC_SIGNAL_WRITE_CHECK=DISABLE`.

Thanks!
