### ISSUE TITLE
Does compiler source code also release?

### ISSUE THREAD

**Issue by anakin1028** [nvdla/sw#62]
This is just a quick question.

From this link: http://nvdla.org/sw/contents.html
umd has `runtime` and `compiler` two components, but under s/w repo I didn't see the source code of compiler? There are only `common, include and runtime` directories.

Thanks for your help!

**Comment by smsharif1991** [comment]
@anakin1028 No we have not released the compiler source code , you can find the binary in prebuilts/linux folder as nvdla_compiler.

Thanks.

**Comment by anakin1028** [comment]
@smsharif1991 thanks :) yes, I have used the prebuilt one.
