### ISSUE TITLE
./nvdla_compiler: line 1: syntax error: unterminated quoted string

### ISSUE THREAD

**Issue by cgl-nudt** [nvdla/sw#74]
Hello,
when I run the code of ./nvdla_compiler under the /mnt/sw-master/prebuilt/linux. I meet some error. but I can run ./nvdla_runtime successfully. I have insmod drm.ko and opendla.ko.

<img width="537" alt="image" src="https://user-images.githubusercontent.com/26371686/42484690-cfb2e788-8426-11e8-88c5-f522386c75ea.png">

**Comment by ShoneAlbert** [comment]
You cannot sovle this problem ever. I think.

**Comment by ShoneAlbert** [comment]
![image](https://user-images.githubusercontent.com/22442214/42485245-68a629ee-8429-11e8-9031-eb348f71a346.png)
I can't solve this problem. It is not about the LD_LIBRARY_PATH.  I hope someone can help me.

**Comment by cgl-nudt** [comment]
@chifredhong Thank you very much!!!
