### ISSUE TITLE
NVDLA VP GPU issue

### ISSUE THREAD

**Issue by ferin08** [nvdla/sw#77]
Hi,

As mentioned in this link: https://en.wikipedia.org/wiki/Direct_Rendering_Manager,
I qoute: `Each GPU detected by DRM is referred as a DRM device, and a device file /dev/dri/cardX (where X is a sequential number) is created to interface with it`

In my laptop, I have already set up NVDLA VP and it works. But the file `/dec/dri/card0` exists even though I don't have a GPU. We don't need a GPU for NVDLA VP right?
Please explain what this means.

**Comment by prasshantg** [comment]
@ferin08 you don't need a GPU. DLA is registered as DRM device and hence it appears as /dev/dri/
