### ISSUE TITLE
Why NVIDIA does not open a source code of the "drm.ko"?

### ISSUE THREAD

**Issue by boiihong** [nvdla/sw#78]
Hello all.

I wonder why there is only header file of the "drm.ko" module.

Currently i'm tracing the sw stack of NVDLA using the Virtual Platform.

In the NvDlaSubmit function, i could find the ioctl function that passes "DRM_IOCTL_NVDLA_SUBMIT" parameter.
I have tried to find the module that has the function called by the very ioctl.
Anyway, i couldn't find function code but only find the header..

Where am i have to go to know what's going on inside of drm.ko?

**Comment by mmaciag** [comment]
Isn't DRM part of Linux kernel? https://github.com/torvalds/linux/tree/master/drivers/gpu/drm
For example I work with PetaLinux, and I am not using drm.ko from the repo at all.

The only binary that evidently won't be ever disclosed is _nvdla_compiler_ (and corresponding .so library) All other stuff (opendla.ko and runtime source) is already here.

**Comment by boiihong** [comment]
@mmaciag  
Thank you very much.
Ok, it is in the linux source.
And also thanks for pointing out what i am finding.. it is helpful for me.
