### ISSUE TITLE
Get a whole Alexnet example running on RTL Simulator

### ISSUE THREAD

**Issue by silvaurus** [nvdla/sw#83]
Hi! It would be great if I can run a whole Alexnet reference example (even just one picture), or even just some layers of Alexnet on RTL simulator. 
I've read from previous issues in the /hw branch (e.g. this one https://github.com/nvdla/hw/issues/89) that currently we don't support generating RTL simulator input directly from compiler output, and don't have plan to support this either.
Yet we do need more RTL simulator tests (such as layers taken from real neuron network examples) than the ones provided.
It would be great if I can get some help or instructions or hints from you.

Thank you so much!

**Comment by prasshantg** [comment]
@silvaurus someone from HW team should be able to help you https://github.com/nvdla/hw

**Comment by wxbbuaa2011** [comment]
@silvaurus  Hello, have you solved your question? I hope to followyour work.

**Comment by vasu123456vasu** [comment]
@silvaurus  have you done it...if yes... please let me know how

**Comment by long771** [comment]
这是来自QQ邮箱的自动回复邮件。 您好，我是龙欣荣，很高兴收到您的邮件，我将尽快处理。
