### ISSUE TITLE
Failed to insmod opendla.ko when changing from 4.13.3 to 4.15

### ISSUE THREAD

**Issue by JunningWu** [nvdla/sw#99]
when I try to change the linux kernel version from the default 4.13.3 to some newer ones such as linux-4.15, I failed to insmod the opendla.ko. 
The whole process is recorded in this link: https://github.com/JunningWu/Learning-NVDLA-Notes/wiki/6.-Linux-Kernel-&-Driver-Development#67-porting-from-default-linux-4133-to-newer-linux-415

```
# insmod ../../images/linux-4.15/opendla.ko 
[ 1747.174820] opendla: loading out-of-tree module taints kernel.
[ 1747.182053] reset engine done
[ 1747.193011] [drm] Initialized nvdla 0.0.0 20171017 for 10200000.nvdla on minor 0
[ 1747.200831] NVDLA 10200000.nvdla: failed to register drm device
[ 1747.202097] NVDLA: probe of 10200000.nvdla failed with error -12
```

**Comment by prasshantg** [comment]
you need to build all 3 components with same kernel version
- kernel image
- drm.ko
- opendla.ko

**Comment by JunningWu** [comment]
Yes, we are. I wonder if we shall change sw source code? And what is the -12 error mean for?

**Comment by JunningWu** [comment]
```
# insmod ../../images/linux-4.15/opendla.ko 
[ 1747.174820] opendla: loading out-of-tree module taints kernel.
[ 1747.182053] reset engine done
[ 1747.193011] [drm] Initialized nvdla 0.0.0 20171017 for 10200000.nvdla on minor 0
[ 1747.200831] NVDLA 10200000.nvdla: failed to register drm device
[ 1747.202097] NVDLA: probe of 10200000.nvdla failed with error -12

# ./nvdla_runtime --loadable basic.nvdla --image img_1.jpg --rawdump
creating new runtime context...
libnvdla<1> failed to open dla device
libnvdla<1> Out of bounds DLA instance 0 requested.
(DLA_TEST) Error 0x00000004: runtime->load failed (in RuntimeTest.cpp, function loadLoadable(), line 343)
(DLA_TEST) Error 0x00000004: (propagating from RuntimeTest.cpp, function run(), line 419)
(DLA_TEST) Error 0x00000004: (propagating from main.cpp, function launchTest(), line 87)
# modprobe opendla
# lsmod
Module                  Size  Used by    Tainted: G  
opendla                81920  0 
drm                   430080  1 opendla
ipv6                  413696 12 [permanent]
```

**Comment by JunningWu** [comment]
@giusecesa4 thanks a lot.

**Comment by peterzh2018888** [comment]
> when I try to change the linux kernel version from the default 4.13.3 to some newer ones such as linux-4.15, I failed to insmod the opendla.ko.
> The whole process is recorded in this link: https://github.com/JunningWu/Learning-NVDLA-Notes/wiki/6.-Linux-Kernel-&-Driver-Development#67-porting-from-default-linux-4133-to-newer-linux-415
> 
> ```
> # insmod ../../images/linux-4.15/opendla.ko 
> [ 1747.174820] opendla: loading out-of-tree module taints kernel.
> [ 1747.182053] reset engine done
> [ 1747.193011] [drm] Initialized nvdla 0.0.0 20171017 for 10200000.nvdla on minor 0
> [ 1747.200831] NVDLA 10200000.nvdla: failed to register drm device
> [ 1747.202097] NVDLA: probe of 10200000.nvdla failed with error -12
> ```

nvdla_small: failed to register drm device

> when I try to change the linux kernel version from the default 4.13.3 to some newer ones such as linux-4.15, I failed to insmod the opendla.ko.
> The whole process is recorded in this link: https://github.com/JunningWu/Learning-NVDLA-Notes/wiki/6.-Linux-Kernel-&-Driver-Development#67-porting-from-default-linux-4133-to-newer-linux-415
> 
> ```
> # insmod ../../images/linux-4.15/opendla.ko 
> [ 1747.174820] opendla: loading out-of-tree module taints kernel.
> [ 1747.182053] reset engine done
> [ 1747.193011] [drm] Initialized nvdla 0.0.0 20171017 for 10200000.nvdla on minor 0
> [ 1747.200831] NVDLA 10200000.nvdla: failed to register drm device
> [ 1747.202097] NVDLA: probe of 10200000.nvdla failed with error -12
> ```

I am running nvdla_small spec on Xiliinx Ultrascale Board ZCU102
But,There's a problem : NVDLA a0000000.nvdla_small: failed to register drm device。
cat /proc/interrupts is also not right。
Why,how to solve it? Do you have the same problem?

**Comment by peterzh2018888** [comment]
> @giusecesa4 thanks a lot.

I am running nvdla_small spec on Xiliinx Ultrascale Board ZCU102
But,There's a problem : NVDLA a0000000.nvdla_small: failed to register drm device。
cat /proc/interrupts is also not right。
Why,how to solve it? who have the same problem?Did you follow [giusecesa4](/giusecesa4) 's proposal and solve it now?

**Comment by peterzh2018888** [comment]
> @JunningWu the error -12 refers to the Linux constant ENOMEM.
> In the file `nvdla_gem.c` you find the function
> 
> > dma_declare_coherent_memory
> 
> this function has been modified in Linux 4.14 (I suppose 4.15 is the same) and it returns the opposite value if the function completes correctly. So, you need to modify the error condition putting
> 
> > if(dma)
> 
> rather than
> 
> > if(!dma)
> 
> Moreover, the constant DMA_MEMORY_MAP does not exists anymore from the Linux version 4.14. You can simply eliminate it

I am running nvdla_small spec on Xiliinx Ultrascale Board ZCU102
But,There's a problem : NVDLA a0000000.nvdla_small: failed to register drm device。
cat /proc/interrupts is also not right。

putting

if(dma)

rather than

if(!dma)

are you sure this can solve it? if(dma)?
